'use strict';
var exports = module.exports = {};

exports.getSpecies = function () {
    return [{"sc": "Dendrocygna viduata", "en": "White-faced Whistling Duck", "sv": "Vithuvad visseland"},
        {"sc": "Anser fabalis", "en": "Taiga Bean Goose", "sv": "tajgasädgås"},
        {"sc": "Anser serrirostris", "en": "Tundra Bean Goose", "sv": "tundrasädgås"},
        {"sc": "Anser brachyrhynchus", "en": "Pink-footed Goose", "sv": "Spetsbergsgås"},
        {"sc": "Anser anser", "en": "Greylag Goose", "sv": "Grågås"},
        {"sc": "Anser albifrons", "en": "Greater White-fronted Goose", "sv": "Bläsgås"},
        {"sc": "Anser erythropus", "en": "Lesser White-fronted Goose", "sv": "Fjällgås"},
        {"sc": "Anser indicus", "en": "Bar-headed Goose", "sv": "Stripgås"},
        {"sc": "Chen caerulescens", "en": "Snow Goose", "sv": "Snögås"},
        {"sc": "Chen rossii", "en": "Ross's Goose", "sv": "Dvärgsnögås"},
        {"sc": "Branta canadensis", "en": "Canada Goose", "sv": "Kanadagås"},
        {"sc": "Branta hutchinsii", "en": "Cackling Goose", "sv": "Dvärgkanadagås"},
        {"sc": "Branta bernicla", "en": "Brant Goose", "sv": "Prutgås"},
        {"sc": "Branta leucopsis", "en": "Barnacle Goose", "sv": "Vitkindad gås"},
        {"sc": "Branta ruficollis", "en": "Red-breasted Goose", "sv": "Rödhalsad gås"},
        {"sc": "Cygnus olor", "en": "Mute Swan", "sv": "Knölsvan"},
        {"sc": "Cygnus columbianus", "en": "Tundra Swan", "sv": "mindre sångsvan"},
        {"sc": "Cygnus cygnus", "en": "Whooper Swan", "sv": "Sångsvan"},
        {"sc": "Alopochen aegyptiaca", "en": "Egyptian Goose", "sv": "Nilgås"},
        {"sc": "Tadorna tadorna", "en": "Common Shelduck", "sv": "Gravand"},
        {"sc": "Tadorna ferruginea", "en": "Ruddy Shelduck", "sv": "Rostand"},
        {"sc": "Aix sponsa", "en": "Wood Duck", "sv": "Brudand"},
        {"sc": "Aix galericulata", "en": "Mandarin Duck", "sv": "Mandarinand"},
        {"sc": "Anas strepera", "en": "Gadwall", "sv": "Snatterand"},
        {"sc": "Anas falcata", "en": "Falcated Duck", "sv": "Praktand"},
        {"sc": "Anas penelope", "en": "Eurasian Wigeon", "sv": "Bläsand"},
        {"sc": "Anas americana", "en": "American Wigeon", "sv": "Amerikansk bläsand"},
        {"sc": "Anas rubripes", "en": "American Black Duck", "sv": "Svartand"},
        {"sc": "Anas platyrhynchos", "en": "Mallard", "sv": "Gräsand"},
        {"sc": "Anas discors", "en": "Blue-winged Teal", "sv": "Blåvingad årta"},
        {"sc": "Anas cyanoptera", "en": "Cinnamon Teal", "sv": "Kanelårta"},
        {"sc": "Anas clypeata", "en": "Northern Shoveler", "sv": "Skedand"},
        {"sc": "Anas acuta", "en": "Northern Pintail", "sv": "Stjärtand"},
        {"sc": "Anas querquedula", "en": "Garganey", "sv": "Årta"},
        {"sc": "Anas formosa", "en": "Baikal Teal", "sv": "Gulkindad kricka"},
        {"sc": "Anas crecca", "en": "Eurasian Teal", "sv": "Kricka"},
        {"sc": "Anas carolinensis", "en": "Green-winged Teal", "sv": "Amerikansk kricka"},
        {"sc": "Marmaronetta angustirostris", "en": "Marbled Duck", "sv": "Marmorand"},
        {"sc": "Netta rufina", "en": "Red-crested Pochard", "sv": "Rödhuvad dykand"},
        {"sc": "Aythya valisineria", "en": "Canvasback", "sv": "Svartnäbbad brunand"},
        {"sc": "Aythya americana", "en": "Redhead", "sv": "Amerikansk brunand"},
        {"sc": "Aythya ferina", "en": "Common Pochard", "sv": "Brunand"},
        {"sc": "Aythya nyroca", "en": "Ferruginous Duck", "sv": "Vitögd dykand"},
        {"sc": "Aythya collaris", "en": "Ring-necked Duck", "sv": "Ringand"},
        {"sc": "Aythya fuligula", "en": "Tufted Duck", "sv": "Vigg"},
        {"sc": "Aythya marila", "en": "Greater Scaup", "sv": "Bergand"},
        {"sc": "Aythya affinis", "en": "Lesser Scaup", "sv": "Mindre bergand"},
        {"sc": "Polysticta stelleri", "en": "Steller's Eider", "sv": "Alförrädare"},
        {"sc": "Somateria fischeri", "en": "Spectacled Eider", "sv": "Glasögonejder"},
        {"sc": "Somateria spectabilis", "en": "King Eider", "sv": "Praktejder"},
        {"sc": "Somateria mollissima", "en": "Common Eider", "sv": "Ejder"},
        {"sc": "Histrionicus histrionicus", "en": "Harlequin Duck", "sv": "Strömand"},
        {"sc": "Melanitta perspicillata", "en": "Surf Scoter", "sv": "Vitnackad svärta"},
        {"sc": "Melanitta fusca", "en": "Velvet Scoter", "sv": "Svärta"},
        {"sc": "Melanitta deglandi", "en": "White-winged Scoter", "sv": "Knölsvärta"},
        {"sc": "Melanitta nigra", "en": "Common Scoter", "sv": "Sjöorre"},
        {"sc": "Melanitta americana", "en": "Black Scoter", "sv": "Amerikansk sjöorre"},
        {"sc": "Clangula hyemalis", "en": "Long-tailed Duck", "sv": "Alfågel"},
        {"sc": "Bucephala albeola", "en": "Bufflehead", "sv": "Buffelhuvud"},
        {"sc": "Bucephala clangula", "en": "Common Goldeneye", "sv": "Knipa"},
        {"sc": "Bucephala islandica", "en": "Barrow's Goldeneye", "sv": "Islandsknipa"},
        {"sc": "Mergellus albellus", "en": "Smew", "sv": "Salskrake"},
        {"sc": "Lophodytes cucullatus", "en": "Hooded Merganser", "sv": "Kamskrake"},
        {"sc": "Mergus merganser", "en": "Common Merganser", "sv": "Storskrake"},
        {"sc": "Mergus serrator", "en": "Red-breasted Merganser", "sv": "Småskrake"},
        {"sc": "Oxyura jamaicensis", "en": "Ruddy Duck", "sv": "Amerikansk kopparand"},
        {"sc": "Oxyura leucocephala", "en": "White-headed Duck", "sv": "Kopparand"},
        {"sc": "Numida meleagris", "en": "Helmeted Guineafowl", "sv": "Hjälmpärlhöna"},
        {"sc": "Callipepla californica", "en": "California Quail", "sv": "Kalifornisk tofsvaktel"},
        {"sc": "Colinus virginianus", "en": "Northern Bobwhite", "sv": "Vitstrupig vaktel"},
        {"sc": "Tetrastes bonasia", "en": "Hazel Grouse", "sv": "Järpe"},
        {"sc": "Tetrao urogallus", "en": "Western Capercaillie", "sv": "Tjäder"},
        {"sc": "Lyrurus tetrix", "en": "Black Grouse", "sv": "Orre"},
        {"sc": "Lagopus muta", "en": "Rock Ptarmigan", "sv": "Fjällripa"},
        {"sc": "Lagopus lagopus", "en": "Willow Ptarmigan", "sv": "Dalripa"},
        {"sc": "Alectoris graeca", "en": "Rock Partridge", "sv": "Stenhöna"},
        {"sc": "Alectoris chukar", "en": "Chukar Partridge", "sv": "Berghöna"},
        {"sc": "Alectoris barbara", "en": "Barbary Partridge", "sv": "Klipphöna"},
        {"sc": "Alectoris rufa", "en": "Red-legged Partridge", "sv": "Rödhöna"},
        {"sc": "Francolinus francolinus", "en": "Black Francolin", "sv": "Svart frankolin"},
        {"sc": "Perdix perdix", "en": "Grey Partridge", "sv": "Rapphöna"},
        {"sc": "Coturnix coturnix", "en": "Common Quail", "sv": "Vaktel"},
        {"sc": "Phasianus colchicus", "en": "Common Pheasant", "sv": "Fasan"},
        {"sc": "Chrysolophus pictus", "en": "Golden Pheasant", "sv": "Guldfasan"},
        {"sc": "Chrysolophus amherstiae", "en": "Lady Amherst's Pheasant", "sv": "Diamantfasan"},
        {"sc": "Gavia stellata", "en": "Red-throated Loon", "sv": "Smålom"},
        {"sc": "Gavia arctica", "en": "Black-throated Loon", "sv": "Storlom"},
        {"sc": "Gavia pacifica", "en": "Pacific Loon", "sv": "Stillahavslom"},
        {"sc": "Gavia immer", "en": "Great Northern Loon", "sv": "Svartnäbbad islom"},
        {"sc": "Gavia adamsii", "en": "Yellow-billed Loon", "sv": "Vitnäbbad islom"},
        {"sc": "Oceanites oceanicus", "en": "Wilson's Storm Petrel", "sv": "Havslöpare"},
        {"sc": "Pelagodroma marina", "en": "White-faced Storm Petrel", "sv": "Fregattstormsvala"},
        {"sc": "Fregetta tropica", "en": "Black-bellied Storm Petrel", "sv": "Svartmagad stormsvala"},
        {"sc": "Diomedea exulans", "en": "Wandering Albatross", "sv": "Vandringsalbatross"},
        {"sc": "Thalassarche melanophris", "en": "Black-browed Albatross", "sv": "Svartbrynad albatross"},
        {"sc": "Thalassarche chlororhynchos", "en": "Atlantic Yellow-nosed Albatross", "sv": "mindre albatross"},
        {"sc": "Hydrobates pelagicus", "en": "European Storm Petrel", "sv": "Stormsvala"},
        {"sc": "Oceanodroma castro", "en": "Band-rumped Storm Petrel", "sv": "Oceanlöpare"},
        {"sc": "Oceanodroma monteiroi", "en": "Monteiro's Storm Petrel", "sv": "monteirostormsvala"},
        {"sc": "Oceanodroma monorhis", "en": "Swinhoe's Storm Petrel", "sv": "Swinhoes stormsvala"},
        {"sc": "Oceanodroma leucorhoa", "en": "Leach's Storm Petrel", "sv": "Klykstjärtad stormsvala"},
        {"sc": "Macronectes giganteus", "en": "Southern Giant Petrel", "sv": "Sydlig jättestormfågel"},
        {"sc": "Fulmarus glacialis", "en": "Northern Fulmar", "sv": "Stormfågel"},
        {"sc": "Daption capense", "en": "Cape Petrel", "sv": "Brokpetrell"},
        {"sc": "Pterodroma incerta", "en": "Atlantic Petrel", "sv": "vitbukig petrell"},
        {"sc": "Pterodroma mollis", "en": "Soft-plumaged Petrel", "sv": "Sammetspetrell"},
        {"sc": "Pterodroma madeira", "en": "Zino's Petrel", "sv": "Madeirapetrell"},
        {"sc": "Pterodroma feae", "en": "Fea's Petrel", "sv": "kapverdepetrell"},
        {"sc": "Pterodroma deserta", "en": "Desertas Petrel", "sv": "desertaspetrell"},
        {"sc": "Pterodroma cahow", "en": "Bermuda Petrel", "sv": "Bermudapetrell"},
        {"sc": "Pterodroma hasitata", "en": "Black-capped Petrel", "sv": "karibpetrell"},
        {"sc": "Pterodroma heraldica", "en": "Herald Petrel", "sv": "heraldpetrell"},
        {"sc": "Pterodroma arminjoniana", "en": "Trindade Petrel", "sv": "Trindadepetrell"},
        {"sc": "Calonectris diomedea", "en": "Scopoli's Shearwater", "sv": "scopolilira"},
        {"sc": "Calonectris borealis", "en": "Cory's Shearwater", "sv": "gulnäbbad lira"},
        {"sc": "Calonectris edwardsii", "en": "Cape Verde Shearwater", "sv": "kapverdelira"},
        {"sc": "Puffinus griseus", "en": "Sooty Shearwater", "sv": "grålira"},
        {"sc": "Puffinus gravis", "en": "Great Shearwater", "sv": "Större lira"},
        {"sc": "Puffinus puffinus", "en": "Manx Shearwater", "sv": "Mindre lira"},
        {"sc": "Puffinus yelkouan", "en": "Yelkouan Shearwater", "sv": "medelhavslira"},
        {"sc": "Puffinus mauretanicus", "en": "Balearic Shearwater", "sv": "balearisk lira"},
        {"sc": "Puffinus bailloni", "en": "Tropical Shearwater", "sv": "tropiklira"},
        {"sc": "Puffinus baroli", "en": "Barolo Shearwater", "sv": "makaronesisk lira"},
        {"sc": "Puffinus boydi", "en": "Boyd's Shearwater", "sv": "boydlira"},
        {"sc": "Bulweria bulwerii", "en": "Bulwer's Petrel", "sv": "Spetsstjärtad petrell"},
        {"sc": "Tachybaptus ruficollis", "en": "Little Grebe", "sv": "Smådopping"},
        {"sc": "Podilymbus podiceps", "en": "Pied-billed Grebe", "sv": "Tjocknäbbad dopping"},
        {"sc": "Podiceps grisegena", "en": "Red-necked Grebe", "sv": "Gråhakedopping"},
        {"sc": "Podiceps cristatus", "en": "Great Crested Grebe", "sv": "Skäggdopping"},
        {"sc": "Podiceps auritus", "en": "Horned Grebe", "sv": "Svarthakedopping"},
        {"sc": "Podiceps nigricollis", "en": "Black-necked Grebe", "sv": "Svarthalsad dopping"},
        {"sc": "Phoenicopterus roseus", "en": "Greater Flamingo", "sv": "Större flamingo"},
        {"sc": "Phoeniconaias minor", "en": "Lesser Flamingo", "sv": "Mindre flamingo"},
        {"sc": "Phaethon aethereus", "en": "Red-billed Tropicbird", "sv": "Rödnäbbad tropikfågel"},
        {"sc": "Phaethon lepturus", "en": "White-tailed Tropicbird", "sv": "Vitstjärtad tropikfågel"},
        {"sc": "Mycteria ibis", "en": "Yellow-billed Stork", "sv": "Afrikansk ibisstork"},
        {"sc": "Ciconia nigra", "en": "Black Stork", "sv": "Svart stork"},
        {"sc": "Ciconia ciconia", "en": "White Stork", "sv": "Vit stork"},
        {"sc": "Leptoptilos crumenifer", "en": "Marabou Stork", "sv": "maraboustork"},
        {"sc": "Threskiornis aethiopicus", "en": "African Sacred Ibis", "sv": "Helig ibis"},
        {"sc": "Geronticus eremita", "en": "Northern Bald Ibis", "sv": "Eremitibis"},
        {"sc": "Geronticus calvus", "en": "Southern Bald Ibis", "sv": "Skallig ibis"},
        {"sc": "Plegadis falcinellus", "en": "Glossy Ibis", "sv": "Bronsibis"},
        {"sc": "Platalea leucorodia", "en": "Eurasian Spoonbill", "sv": "Skedstork"},
        {"sc": "Platalea alba", "en": "African Spoonbill", "sv": "Afrikansk skedstork"},
        {"sc": "Botaurus stellaris", "en": "Eurasian Bittern", "sv": "Rördrom"},
        {"sc": "Botaurus lentiginosus", "en": "American Bittern", "sv": "amerikansk rördrom"},
        {"sc": "Ixobrychus exilis", "en": "Least Bittern", "sv": "Amerikansk dvärgrördrom"},
        {"sc": "Ixobrychus minutus", "en": "Little Bittern", "sv": "Dvärgrördrom"},
        {"sc": "Ixobrychus eurhythmus", "en": "Von Schrenck's Bittern", "sv": "Schrencks dvärgrördrom"},
        {"sc": "Ixobrychus sturmii", "en": "Dwarf Bittern", "sv": "Pygmérördrom"},
        {"sc": "Nycticorax nycticorax", "en": "Black-crowned Night Heron", "sv": "Natthäger"},
        {"sc": "Nyctanassa violacea", "en": "Yellow-crowned Night Heron", "sv": "Gulkronad natthäger"},
        {"sc": "Butorides virescens", "en": "Green Heron", "sv": "grönryggig häger"},
        {"sc": "Butorides striata", "en": "Striated Heron", "sv": "Mangrovehäger"},
        {"sc": "Ardeola ralloides", "en": "Squacco Heron", "sv": "Rallhäger"},
        {"sc": "Ardeola grayii", "en": "Indian Pond Heron", "sv": "Rishäger"},
        {"sc": "Ardeola bacchus", "en": "Chinese Pond Heron", "sv": "Bacchushäger"},
        {"sc": "Bubulcus ibis", "en": "Western Cattle Egret", "sv": "Kohäger"},
        {"sc": "Ardea cinerea", "en": "Grey Heron", "sv": "Gråhäger"},
        {"sc": "Ardea herodias", "en": "Great Blue Heron", "sv": "Amerikansk gråhäger"},
        {"sc": "Ardea melanocephala", "en": "Black-headed Heron", "sv": "Svarthuvad häger"},
        {"sc": "Ardea purpurea", "en": "Purple Heron", "sv": "Purpurhäger"},
        {"sc": "Ardea alba", "en": "Great Egret", "sv": "Ägretthäger"},
        {"sc": "Egretta ardesiaca", "en": "Black Heron", "sv": "Svarthäger"},
        {"sc": "Egretta tricolor", "en": "Tricolored Heron", "sv": "Trefärgad häger"},
        {"sc": "Egretta caerulea", "en": "Little Blue Heron", "sv": "Blåhäger"},
        {"sc": "Egretta thula", "en": "Snowy Egret", "sv": "Snöhäger"},
        {"sc": "Egretta garzetta", "en": "Little Egret", "sv": "Silkeshäger"},
        {"sc": "Egretta gularis", "en": "Western Reef Heron", "sv": "Revhäger"},
        {"sc": "Pelecanus onocrotalus", "en": "Great White Pelican", "sv": "Vit pelikan"},
        {"sc": "Pelecanus crispus", "en": "Dalmatian Pelican", "sv": "Krushuvad pelikan"},
        {"sc": "Fregata aquila", "en": "Ascension Frigatebird", "sv": "Ascensionfregattfågel"},
        {"sc": "Fregata magnificens", "en": "Magnificent Frigatebird", "sv": "praktfregattfågel"},
        {"sc": "Morus bassanus", "en": "Northern Gannet", "sv": "Havssula"},
        {"sc": "Morus capensis", "en": "Cape Gannet", "sv": "Kapsula"},
        {"sc": "Sula dactylatra", "en": "Masked Booby", "sv": "Masksula"},
        {"sc": "Sula sula", "en": "Red-footed Booby", "sv": "Rödfotad sula"},
        {"sc": "Sula leucogaster", "en": "Brown Booby", "sv": "brun sula"},
        {"sc": "Microcarbo pygmeus", "en": "Pygmy Cormorant", "sv": "Dvärgskarv"},
        {"sc": "Phalacrocorax auritus", "en": "Double-crested Cormorant", "sv": "Öronskarv"},
        {"sc": "Phalacrocorax aristotelis", "en": "European Shag", "sv": "Toppskarv"},
        {"sc": "Phalacrocorax carbo", "en": "Great Cormorant", "sv": "storskarv"},
        {"sc": "Phalacrocorax lucidus", "en": "White-breasted Cormorant", "sv": "vitbröstad skarv"},
        {"sc": "Anhinga rufa", "en": "African Darter", "sv": "Afrikansk ormhalsfågel"},
        {"sc": "Pandion haliaetus", "en": "Western Osprey", "sv": "Fiskgjuse"},
        {"sc": "Elanus caeruleus", "en": "Black-winged Kite", "sv": "Svartvingad glada"},
        {"sc": "Gypaetus barbatus", "en": "Bearded Vulture", "sv": "Lammgam"},
        {"sc": "Neophron percnopterus", "en": "Egyptian Vulture", "sv": "Smutsgam"},
        {"sc": "Pernis apivorus", "en": "European Honey Buzzard", "sv": "Bivråk"},
        {"sc": "Pernis ptilorhynchus", "en": "Crested Honey Buzzard", "sv": "Tofsbivråk"},
        {"sc": "Elanoides forficatus", "en": "Swallow-tailed Kite", "sv": "Svalstjärtsglada"},
        {"sc": "Gyps africanus", "en": "White-backed Vulture", "sv": "vitryggig gam"},
        {"sc": "Gyps rueppelli", "en": "Rüppell's Vulture", "sv": "Rüppellgam"},
        {"sc": "Gyps fulvus", "en": "Griffon Vulture", "sv": "Gåsgam"},
        {"sc": "Aegypius monachus", "en": "Cinereous Vulture", "sv": "Grågam"},
        {"sc": "Torgos tracheliotos", "en": "Lappet-faced Vulture", "sv": "Örongam"},
        {"sc": "Circaetus gallicus", "en": "Short-toed Snake Eagle", "sv": "Ormörn"},
        {"sc": "Clanga pomarina", "en": "Lesser Spotted Eagle", "sv": "Mindre skrikörn"},
        {"sc": "Clanga clanga", "en": "Greater Spotted Eagle", "sv": "Större skrikörn"},
        {"sc": "Hieraaetus pennatus", "en": "Booted Eagle", "sv": "Dvärgörn"},
        {"sc": "Aquila nipalensis", "en": "Steppe Eagle", "sv": "Stäppörn"},
        {"sc": "Aquila adalberti", "en": "Spanish Imperial Eagle", "sv": "Spansk kejsarörn"},
        {"sc": "Aquila heliaca", "en": "Eastern Imperial Eagle", "sv": "Kejsarörn"},
        {"sc": "Aquila chrysaetos", "en": "Golden Eagle", "sv": "Kungsörn"},
        {"sc": "Aquila fasciata", "en": "Bonelli's Eagle", "sv": "Hökörn"},
        {"sc": "Accipiter brevipes", "en": "Levant Sparrowhawk", "sv": "Balkanhök"},
        {"sc": "Accipiter nisus", "en": "Eurasian Sparrowhawk", "sv": "Sparvhök"},
        {"sc": "Accipiter gentilis", "en": "Northern Goshawk", "sv": "Duvhök"},
        {"sc": "Circus aeruginosus", "en": "Western Marsh Harrier", "sv": "Brun kärrhök"},
        {"sc": "Circus cyaneus", "en": "Hen Harrier", "sv": "Blå kärrhök"},
        {"sc": "Circus hudsonius", "en": "Northern Harrier", "sv": "amerikansk kärrhök"},
        {"sc": "Circus macrourus", "en": "Pallid Harrier", "sv": "Stäpphök"},
        {"sc": "Circus pygargus", "en": "Montagu's Harrier", "sv": "Ängshök"},
        {"sc": "Milvus milvus", "en": "Red Kite", "sv": "Röd glada"},
        {"sc": "Milvus migrans", "en": "Black Kite", "sv": "brun glada"},
        {"sc": "Haliaeetus leucoryphus", "en": "Pallas's Fish Eagle", "sv": "Bandhavsörn"},
        {"sc": "Haliaeetus albicilla", "en": "White-tailed Eagle", "sv": "Havsörn"},
        {"sc": "Haliaeetus leucocephalus", "en": "Bald Eagle", "sv": "Vithövdad havsörn"},
        {"sc": "Buteo lagopus", "en": "Rough-legged Buzzard", "sv": "Fjällvråk"},
        {"sc": "Buteo hemilasius", "en": "Upland Buzzard", "sv": "Mongolvråk"},
        {"sc": "Buteo rufinus", "en": "Long-legged Buzzard", "sv": "Örnvråk"},
        {"sc": "Buteo buteo", "en": "Common Buzzard", "sv": "Ormvråk"},
        {"sc": "Otis tarda", "en": "Great Bustard", "sv": "Stortrapp"},
        {"sc": "Chlamydotis undulata", "en": "Houbara Bustard", "sv": "Ökentrapp"},
        {"sc": "Chlamydotis macqueenii", "en": "Macqueen's Bustard", "sv": "Kragtrapp"},
        {"sc": "Tetrax tetrax", "en": "Little Bustard", "sv": "Småtrapp"},
        {"sc": "Rallus limicola", "en": "Virginia Rail", "sv": "Virginiarall"},
        {"sc": "Rallus aquaticus", "en": "Water Rail", "sv": "Vattenrall"},
        {"sc": "Crex egregia", "en": "African Crake", "sv": "Afrikansk kornknarr"},
        {"sc": "Crex crex", "en": "Corn Crake", "sv": "Kornknarr"},
        {"sc": "Amaurornis flavirostra", "en": "Black Crake", "sv": "Korprall"},
        {"sc": "Porzana parva", "en": "Little Crake", "sv": "Mindre sumphöna"},
        {"sc": "Porzana pusilla", "en": "Baillon's Crake", "sv": "Dvärgsumphöna"},
        {"sc": "Porzana porzana", "en": "Spotted Crake", "sv": "Småfläckig sumphöna"},
        {"sc": "Porzana carolina", "en": "Sora", "sv": "Karolinasumphöna"},
        {"sc": "Aenigmatolimnas marginalis", "en": "Striped Crake", "sv": "Rostgumpad sumphöna"},
        {"sc": "Porphyrio porphyrio", "en": "Purple Swamphen", "sv": "Purpurhöna"},
        {"sc": "Porphyrio madagascariensis", "en": "African Swamphen", "sv": "afrikansk purpurhöna"},
        {"sc": "Porphyrio alleni", "en": "Allen's Gallinule", "sv": "Mindre sultanhöna"},
        {"sc": "Porphyrio martinicus", "en": "Purple Gallinule", "sv": "Amerikansk sultanhöna"},
        {"sc": "Gallinula chloropus", "en": "Common Moorhen", "sv": "Rörhöna"},
        {"sc": "Gallinula galeata", "en": "Common Gallinule", "sv": "amerikansk rörhöna"},
        {"sc": "Gallinula angulata", "en": "Lesser Moorhen", "sv": "Mindre rörhöna"},
        {"sc": "Fulica cristata", "en": "Red-knobbed Coot", "sv": "Kamsothöna"},
        {"sc": "Fulica atra", "en": "Eurasian Coot", "sv": "Sothöna"},
        {"sc": "Fulica americana", "en": "American Coot", "sv": "amerikansk sothöna"},
        {"sc": "Grus leucogeranus", "en": "Siberian Crane", "sv": "Snötrana"},
        {"sc": "Grus canadensis", "en": "Sandhill Crane", "sv": "Prärietrana"},
        {"sc": "Grus virgo", "en": "Demoiselle Crane", "sv": "Jungfrutrana"},
        {"sc": "Grus grus", "en": "Common Crane", "sv": "Trana"},
        {"sc": "Grus monacha", "en": "Hooded Crane", "sv": "Munktrana"},
        {"sc": "Turnix sylvaticus", "en": "Common Buttonquail", "sv": "Springhöna"},
        {"sc": "Burhinus oedicnemus", "en": "Eurasian Stone-curlew", "sv": "Tjockfot"},
        {"sc": "Haematopus palliatus", "en": "American Oystercatcher", "sv": "Amerikansk strandskata"},
        {"sc": "Haematopus meadewaldoi", "en": "Canary Islands Oystercatcher", "sv": "Kanariestrandskata"},
        {"sc": "Haematopus ostralegus", "en": "Eurasian Oystercatcher", "sv": "Strandskata"},
        {"sc": "Himantopus himantopus", "en": "Black-winged Stilt", "sv": "Styltlöpare"},
        {"sc": "Recurvirostra avosetta", "en": "Pied Avocet", "sv": "Skärfläcka"},
        {"sc": "Recurvirostra americana", "en": "American Avocet", "sv": "Amerikansk skärfläcka"},
        {"sc": "Vanellus vanellus", "en": "Northern Lapwing", "sv": "Tofsvipa"},
        {"sc": "Vanellus spinosus", "en": "Spur-winged Lapwing", "sv": "Sporrvipa"},
        {"sc": "Vanellus gregarius", "en": "Sociable Lapwing", "sv": "Stäppvipa"},
        {"sc": "Vanellus leucurus", "en": "White-tailed Lapwing", "sv": "Sumpvipa"},
        {"sc": "Pluvialis apricaria", "en": "European Golden Plover", "sv": "Ljungpipare"},
        {"sc": "Pluvialis fulva", "en": "Pacific Golden Plover", "sv": "Sibirisk tundrapipare"},
        {"sc": "Pluvialis dominica", "en": "American Golden Plover", "sv": "Amerikansk tundrapipare"},
        {"sc": "Pluvialis squatarola", "en": "Grey Plover", "sv": "Kustpipare"},
        {"sc": "Charadrius hiaticula", "en": "Common Ringed Plover", "sv": "Större strandpipare"},
        {"sc": "Charadrius semipalmatus", "en": "Semipalmated Plover", "sv": "Flikstrandpipare"},
        {"sc": "Charadrius dubius", "en": "Little Ringed Plover", "sv": "Mindre strandpipare"},
        {"sc": "Charadrius vociferus", "en": "Killdeer", "sv": "Skrikstrandpipare"},
        {"sc": "Charadrius pecuarius", "en": "Kittlitz's Plover", "sv": "Kittlitzstrandpipare"},
        {"sc": "Charadrius alexandrinus", "en": "Kentish Plover", "sv": "Svartbent strandpipare"},
        {"sc": "Charadrius mongolus", "en": "Lesser Sand Plover", "sv": "Mongolpipare"},
        {"sc": "Charadrius leschenaultii", "en": "Greater Sand Plover", "sv": "Ökenpipare"},
        {"sc": "Charadrius asiaticus", "en": "Caspian Plover", "sv": "Kaspisk pipare"},
        {"sc": "Charadrius veredus", "en": "Oriental Plover", "sv": "Orientpipare"},
        {"sc": "Charadrius morinellus", "en": "Eurasian Dotterel", "sv": "Fjällpipare"},
        {"sc": "Scolopax rusticola", "en": "Eurasian Woodcock", "sv": "Morkulla"},
        {"sc": "Scolopax minor", "en": "American Woodcock", "sv": "Amerikansk morkulla"},
        {"sc": "Lymnocryptes minimus", "en": "Jack Snipe", "sv": "Dvärgbeckasin"},
        {"sc": "Gallinago stenura", "en": "Pin-tailed Snipe", "sv": "Sibirisk beckasin"},
        {"sc": "Gallinago megala", "en": "Swinhoe's Snipe", "sv": "tajgabeckasin"},
        {"sc": "Gallinago media", "en": "Great Snipe", "sv": "Dubbelbeckasin"},
        {"sc": "Gallinago gallinago", "en": "Common Snipe", "sv": "Enkelbeckasin"},
        {"sc": "Gallinago delicata", "en": "Wilson's Snipe", "sv": "Wilsonbeckasin"},
        {"sc": "Limnodromus griseus", "en": "Short-billed Dowitcher", "sv": "mindre beckasinsnäppa"},
        {"sc": "Limnodromus scolopaceus", "en": "Long-billed Dowitcher", "sv": "större beckasinsnäppa"},
        {"sc": "Limosa limosa", "en": "Black-tailed Godwit", "sv": "Rödspov"},
        {"sc": "Limosa haemastica", "en": "Hudsonian Godwit", "sv": "Hudsonspov"},
        {"sc": "Limosa lapponica", "en": "Bar-tailed Godwit", "sv": "Myrspov"},
        {"sc": "Numenius minutus", "en": "Little Curlew", "sv": "Dvärgspov"},
        {"sc": "Numenius borealis", "en": "Eskimo Curlew", "sv": "Eskimåspov"},
        {"sc": "Numenius phaeopus", "en": "Whimbrel", "sv": "Småspov"},
        {"sc": "Numenius tenuirostris", "en": "Slender-billed Curlew", "sv": "Smalnäbbad spov"},
        {"sc": "Numenius arquata", "en": "Eurasian Curlew", "sv": "Storspov"},
        {"sc": "Bartramia longicauda", "en": "Upland Sandpiper", "sv": "Piparsnäppa"},
        {"sc": "Tringa erythropus", "en": "Spotted Redshank", "sv": "Svartsnäppa"},
        {"sc": "Tringa totanus", "en": "Common Redshank", "sv": "Rödbena"},
        {"sc": "Tringa stagnatilis", "en": "Marsh Sandpiper", "sv": "Dammsnäppa"},
        {"sc": "Tringa nebularia", "en": "Common Greenshank", "sv": "Gluttsnäppa"},
        {"sc": "Tringa melanoleuca", "en": "Greater Yellowlegs", "sv": "Större gulbena"},
        {"sc": "Tringa flavipes", "en": "Lesser Yellowlegs", "sv": "Mindre gulbena"},
        {"sc": "Tringa ochropus", "en": "Green Sandpiper", "sv": "Skogssnäppa"},
        {"sc": "Tringa solitaria", "en": "Solitary Sandpiper", "sv": "Amerikansk skogssnäppa"},
        {"sc": "Tringa glareola", "en": "Wood Sandpiper", "sv": "Grönbena"},
        {"sc": "Tringa brevipes", "en": "Grey-tailed Tattler", "sv": "Sibirisk gråsnäppa"},
        {"sc": "Tringa semipalmata", "en": "Willet", "sv": "willet"},
        {"sc": "Xenus cinereus", "en": "Terek Sandpiper", "sv": "Tereksnäppa"},
        {"sc": "Actitis hypoleucos", "en": "Common Sandpiper", "sv": "Drillsnäppa"},
        {"sc": "Actitis macularius", "en": "Spotted Sandpiper", "sv": "Fläckdrillsnäppa"},
        {"sc": "Arenaria interpres", "en": "Ruddy Turnstone", "sv": "Roskarl"},
        {"sc": "Calidris tenuirostris", "en": "Great Knot", "sv": "Kolymasnäppa"},
        {"sc": "Calidris canutus", "en": "Red Knot", "sv": "Kustsnäppa"},
        {"sc": "Calidris alba", "en": "Sanderling", "sv": "Sandlöpare"},
        {"sc": "Calidris pusilla", "en": "Semipalmated Sandpiper", "sv": "Sandsnäppa"},
        {"sc": "Calidris mauri", "en": "Western Sandpiper", "sv": "Tundrasnäppa"},
        {"sc": "Calidris ruficollis", "en": "Red-necked Stint", "sv": "Rödhalsad snäppa"},
        {"sc": "Calidris minuta", "en": "Little Stint", "sv": "Småsnäppa"},
        {"sc": "Calidris temminckii", "en": "Temminck's Stint", "sv": "Mosnäppa"},
        {"sc": "Calidris subminuta", "en": "Long-toed Stint", "sv": "Långtåsnäppa"},
        {"sc": "Calidris minutilla", "en": "Least Sandpiper", "sv": "Dvärgsnäppa"},
        {"sc": "Calidris fuscicollis", "en": "White-rumped Sandpiper", "sv": "Vitgumpsnäppa"},
        {"sc": "Calidris bairdii", "en": "Baird's Sandpiper", "sv": "Gulbröstad snäppa"},
        {"sc": "Calidris melanotos", "en": "Pectoral Sandpiper", "sv": "Tuvsnäppa"},
        {"sc": "Calidris acuminata", "en": "Sharp-tailed Sandpiper", "sv": "Spetsstjärtad snäppa"},
        {"sc": "Calidris ferruginea", "en": "Curlew Sandpiper", "sv": "Spovsnäppa"},
        {"sc": "Calidris maritima", "en": "Purple Sandpiper", "sv": "Skärsnäppa"},
        {"sc": "Calidris alpina", "en": "Dunlin", "sv": "Kärrsnäppa"},
        {"sc": "Calidris himantopus", "en": "Stilt Sandpiper", "sv": "Styltsnäppa"},
        {"sc": "Eurynorhynchus pygmeus", "en": "Spoon-billed Sandpiper", "sv": "Skedsnäppa"},
        {"sc": "Limicola falcinellus", "en": "Broad-billed Sandpiper", "sv": "Myrsnäppa"},
        {"sc": "Tryngites subruficollis", "en": "Buff-breasted Sandpiper", "sv": "Prärielöpare"},
        {"sc": "Philomachus pugnax", "en": "Ruff", "sv": "Brushane"},
        {"sc": "Phalaropus tricolor", "en": "Wilson's Phalarope", "sv": "Wilsonsimsnäppa"},
        {"sc": "Phalaropus lobatus", "en": "Red-necked Phalarope", "sv": "Smalnäbbad simsnäppa"},
        {"sc": "Phalaropus fulicarius", "en": "Red Phalarope", "sv": "Brednäbbad simsnäppa"},
        {"sc": "Cursorius cursor", "en": "Cream-colored Courser", "sv": "Ökenlöpare"},
        {"sc": "Glareola pratincola", "en": "Collared Pratincole", "sv": "Rödvingad vadarsvala"},
        {"sc": "Glareola maldivarum", "en": "Oriental Pratincole", "sv": "Orientvadarsvala"},
        {"sc": "Glareola nordmanni", "en": "Black-winged Pratincole", "sv": "Svartvingad vadarsvala"},
        {"sc": "Anous stolidus", "en": "Brown Noddy", "sv": "Brun noddy"},
        {"sc": "Rynchops niger", "en": "Black Skimmer", "sv": "Amerikansk saxnäbb"},
        {"sc": "Rissa tridactyla", "en": "Black-legged Kittiwake", "sv": "Tretåig mås"},
        {"sc": "Pagophila eburnea", "en": "Ivory Gull", "sv": "Ismås"},
        {"sc": "Xema sabini", "en": "Sabine's Gull", "sv": "Tärnmås"},
        {"sc": "Chroicocephalus genei", "en": "Slender-billed Gull", "sv": "Långnäbbad mås"},
        {"sc": "Chroicocephalus philadelphia", "en": "Bonaparte's Gull", "sv": "Trädmås"},
        {"sc": "Chroicocephalus ridibundus", "en": "Black-headed Gull", "sv": "Skrattmås"},
        {"sc": "Chroicocephalus cirrocephalus", "en": "Grey-headed Gull", "sv": "Gråhuvad mås"},
        {"sc": "Hydrocoloeus minutus", "en": "Little Gull", "sv": "Dvärgmås"},
        {"sc": "Rhodostethia rosea", "en": "Ross's Gull", "sv": "Rosenmås"},
        {"sc": "Leucophaeus atricilla", "en": "Laughing Gull", "sv": "Sotvingad mås"},
        {"sc": "Leucophaeus pipixcan", "en": "Franklin's Gull", "sv": "Präriemås"},
        {"sc": "Ichthyaetus relictus", "en": "Relict Gull", "sv": "Reliktmås"},
        {"sc": "Ichthyaetus audouinii", "en": "Audouin's Gull", "sv": "Rödnäbbad trut"},
        {"sc": "Ichthyaetus melanocephalus", "en": "Mediterranean Gull", "sv": "Svarthuvad mås"},
        {"sc": "Ichthyaetus ichthyaetus", "en": "Pallas's Gull", "sv": "Svarthuvad trut"},
        {"sc": "Ichthyaetus leucophthalmus", "en": "White-eyed Gull", "sv": "Vitögd mås"},
        {"sc": "Larus canus", "en": "Mew Gull", "sv": "Fiskmås"},
        {"sc": "Larus delawarensis", "en": "Ring-billed Gull", "sv": "Ringnäbbad mås"},
        {"sc": "Larus marinus", "en": "Great Black-backed Gull", "sv": "Havstrut"},
        {"sc": "Larus dominicanus", "en": "Kelp Gull", "sv": "kelptrut"},
        {"sc": "Larus hyperboreus", "en": "Glaucous Gull", "sv": "Vittrut"},
        {"sc": "Larus glaucoides", "en": "Iceland Gull", "sv": "Vitvingad trut"},
        {"sc": "Larus thayeri", "en": "Thayer's Gull", "sv": "Thayertrut"},
        {"sc": "Larus argentatus", "en": "European Herring Gull", "sv": "Gråtrut"},
        {"sc": "Larus smithsonianus", "en": "American Herring Gull", "sv": "kanadatrut"},
        {"sc": "Larus cachinnans", "en": "Caspian Gull", "sv": "Kaspisk trut"},
        {"sc": "Larus michahellis", "en": "Yellow-legged Gull", "sv": "Medelhavstrut"},
        {"sc": "Larus armenicus", "en": "Armenian Gull", "sv": "Armenisk trut"},
        {"sc": "Larus schistisagus", "en": "Slaty-backed Gull", "sv": "Skiffertrut"},
        {"sc": "Larus fuscus", "en": "Lesser Black-backed Gull", "sv": "silltrut"},
        {"sc": "Gelochelidon nilotica", "en": "Gull-billed Tern", "sv": "Sandtärna"},
        {"sc": "Hydroprogne caspia", "en": "Caspian Tern", "sv": "Skräntärna"},
        {"sc": "Thalasseus maximus", "en": "Royal Tern", "sv": "Kungstärna"},
        {"sc": "Thalasseus elegans", "en": "Elegant Tern", "sv": "Aztektärna"},
        {"sc": "Thalasseus bengalensis", "en": "Lesser Crested Tern", "sv": "Iltärna"},
        {"sc": "Thalasseus sandvicensis", "en": "Sandwich Tern", "sv": "Kentsk tärna"},
        {"sc": "Thalasseus acuflavidus", "en": "Cabot's Tern", "sv": "Cabots tärna"},
        {"sc": "Sternula albifrons", "en": "Little Tern", "sv": "Småtärna"},
        {"sc": "Sternula saundersi", "en": "Saunders's Tern", "sv": "Saunders småtärna"},
        {"sc": "Sternula antillarum", "en": "Least Tern", "sv": "Amerikansk småtärna"},
        {"sc": "Onychoprion aleuticus", "en": "Aleutian Tern", "sv": "Beringtärna"},
        {"sc": "Onychoprion anaethetus", "en": "Bridled Tern", "sv": "Tygeltärna"},
        {"sc": "Onychoprion fuscatus", "en": "Sooty Tern", "sv": "Sottärna"},
        {"sc": "Sterna dougallii", "en": "Roseate Tern", "sv": "Rosentärna"},
        {"sc": "Sterna hirundo", "en": "Common Tern", "sv": "Fisktärna"},
        {"sc": "Sterna paradisaea", "en": "Arctic Tern", "sv": "Silvertärna"},
        {"sc": "Sterna forsteri", "en": "Forster's Tern", "sv": "Kärrtärna"},
        {"sc": "Chlidonias hybrida", "en": "Whiskered Tern", "sv": "Skäggtärna"},
        {"sc": "Chlidonias leucopterus", "en": "White-winged Tern", "sv": "Vitvingad tärna"},
        {"sc": "Chlidonias niger", "en": "Black Tern", "sv": "Svarttärna"},
        {"sc": "Stercorarius maccormicki", "en": "South Polar Skua", "sv": "Sydpolslabb"},
        {"sc": "Stercorarius skua", "en": "Great Skua", "sv": "Storlabb"},
        {"sc": "Stercorarius pomarinus", "en": "Pomarine Skua", "sv": "Bredstjärtad labb"},
        {"sc": "Stercorarius parasiticus", "en": "Parasitic Jaeger", "sv": "Kustlabb"},
        {"sc": "Stercorarius longicaudus", "en": "Long-tailed Jaeger", "sv": "Fjällabb"},
        {"sc": "Alle alle", "en": "Little Auk", "sv": "Alkekung"},
        {"sc": "Uria lomvia", "en": "Thick-billed Murre", "sv": "Spetsbergsgrissla"},
        {"sc": "Uria aalge", "en": "Common Murre", "sv": "Sillgrissla"},
        {"sc": "Alca torda", "en": "Razorbill", "sv": "Tordmule"},
        {"sc": "Pinguinus impennis", "en": "Great Auk", "sv": "Garfågel"},
        {"sc": "Cepphus grylle", "en": "Black Guillemot", "sv": "Tobisgrissla"},
        {"sc": "Cepphus columba", "en": "Pigeon Guillemot", "sv": "Beringtejst"},
        {"sc": "Brachyramphus perdix", "en": "Long-billed Murrelet", "sv": "Långnäbbad marmoralka"},
        {"sc": "Synthliboramphus antiquus", "en": "Ancient Murrelet", "sv": "Kragalka"},
        {"sc": "Aethia psittacula", "en": "Parakeet Auklet", "sv": "Papegojalka"},
        {"sc": "Aethia cristatella", "en": "Crested Auklet", "sv": "Tofsalka"},
        {"sc": "Fratercula arctica", "en": "Atlantic Puffin", "sv": "Lunnefågel"},
        {"sc": "Fratercula cirrhata", "en": "Tufted Puffin", "sv": "Tofslunne"},
        {"sc": "Syrrhaptes paradoxus", "en": "Pallas's Sandgrouse", "sv": "stäppflyghöna"},
        {"sc": "Pterocles alchata", "en": "Pin-tailed Sandgrouse", "sv": "vitbukig flyghöna"},
        {"sc": "Pterocles orientalis", "en": "Black-bellied Sandgrouse", "sv": "svartbukig flyghöna"},
        {"sc": "Columba livia", "en": "Rock Dove", "sv": "Klippduva"},
        {"sc": "Columba oenas", "en": "Stock Dove", "sv": "Skogsduva"},
        {"sc": "Columba palumbus", "en": "Common Wood Pigeon", "sv": "Ringduva"},
        {"sc": "Columba trocaz", "en": "Trocaz Pigeon", "sv": "Madeiraduva"},
        {"sc": "Columba bollii", "en": "Bolle's Pigeon", "sv": "Kanarieduva"},
        {"sc": "Columba junoniae", "en": "Laurel Pigeon", "sv": "Lagerduva"},
        {"sc": "Streptopelia turtur", "en": "European Turtle Dove", "sv": "Turturduva"},
        {"sc": "Streptopelia orientalis", "en": "Oriental Turtle Dove", "sv": "Större turturduva"},
        {"sc": "Streptopelia decaocto", "en": "Eurasian Collared Dove", "sv": "Turkduva"},
        {"sc": "Streptopelia roseogrisea", "en": "African Collared Dove", "sv": "Skrattduva"},
        {"sc": "Spilopelia senegalensis", "en": "Laughing Dove", "sv": "Palmduva"},
        {"sc": "Ectopistes migratorius", "en": "Passenger Pigeon", "sv": "Vandringsduva"},
        {"sc": "Zenaida macroura", "en": "Mourning Dove", "sv": "Spetsstjärtad duva"},
        {"sc": "Clamator glandarius", "en": "Great Spotted Cuckoo", "sv": "Skatgök"},
        {"sc": "Coccyzus americanus", "en": "Yellow-billed Cuckoo", "sv": "Gulnäbbad regngök"},
        {"sc": "Coccyzus erythropthalmus", "en": "Black-billed Cuckoo", "sv": "Svartnäbbad regngök"},
        {"sc": "Cuculus optatus", "en": "Oriental Cuckoo", "sv": "tajgagök"},
        {"sc": "Cuculus canorus", "en": "Common Cuckoo", "sv": "Gök"},
        {"sc": "Tyto alba", "en": "Western Barn Owl", "sv": "tornuggla"},
        {"sc": "Otus scops", "en": "Eurasian Scops Owl", "sv": "Dvärguv"},
        {"sc": "Bubo scandiacus", "en": "Snowy Owl", "sv": "Fjälluggla"},
        {"sc": "Bubo bubo", "en": "Eurasian Eagle-Owl", "sv": "Berguv"},
        {"sc": "Strix aluco", "en": "Tawny Owl", "sv": "Kattuggla"},
        {"sc": "Strix uralensis", "en": "Ural Owl", "sv": "Slaguggla"},
        {"sc": "Strix nebulosa", "en": "Great Grey Owl", "sv": "Lappuggla"},
        {"sc": "Surnia ulula", "en": "Northern Hawk-Owl", "sv": "Hökuggla"},
        {"sc": "Glaucidium passerinum", "en": "Eurasian Pygmy Owl", "sv": "Sparvuggla"},
        {"sc": "Athene noctua", "en": "Little Owl", "sv": "Minervauggla"},
        {"sc": "Aegolius funereus", "en": "Boreal Owl", "sv": "Pärluggla"},
        {"sc": "Asio otus", "en": "Long-eared Owl", "sv": "Hornuggla"},
        {"sc": "Asio flammeus", "en": "Short-eared Owl", "sv": "Jorduggla"},
        {"sc": "Asio capensis", "en": "Marsh Owl", "sv": "Kapuggla"},
        {"sc": "Chordeiles minor", "en": "Common Nighthawk", "sv": "Större falknattskärra"},
        {"sc": "Caprimulgus ruficollis", "en": "Red-necked Nightjar", "sv": "Rödhalsad nattskärra"},
        {"sc": "Caprimulgus europaeus", "en": "European Nightjar", "sv": "Nattskärra"},
        {"sc": "Caprimulgus aegyptius", "en": "Egyptian Nightjar", "sv": "Ökennattskärra"},
        {"sc": "Hirundapus caudacutus", "en": "White-throated Needletail", "sv": "taggstjärtseglare"},
        {"sc": "Chaetura pelagica", "en": "Chimney Swift", "sv": "Skorstensseglare"},
        {"sc": "Tachymarptis melba", "en": "Alpine Swift", "sv": "Alpseglare"},
        {"sc": "Apus apus", "en": "Common Swift", "sv": "Tornseglare"},
        {"sc": "Apus unicolor", "en": "Plain Swift", "sv": "Enfärgad seglare"},
        {"sc": "Apus pallidus", "en": "Pallid Swift", "sv": "Blek tornseglare"},
        {"sc": "Apus pacificus", "en": "Pacific Swift", "sv": "Orientseglare"},
        {"sc": "Apus affinis", "en": "Little Swift", "sv": "Stubbstjärtseglare"},
        {"sc": "Apus caffer", "en": "White-rumped Swift", "sv": "vitgumpseglare"},
        {"sc": "Coracias abyssinicus", "en": "Abyssinian Roller", "sv": "Savannblåkråka"},
        {"sc": "Coracias garrulus", "en": "European Roller", "sv": "Blåkråka"},
        {"sc": "Halcyon smyrnensis", "en": "White-throated Kingfisher", "sv": "Smyrnakungsfiskare"},
        {"sc": "Alcedo atthis", "en": "Common Kingfisher", "sv": "Kungsfiskare"},
        {"sc": "Megaceryle alcyon", "en": "Belted Kingfisher", "sv": "Bälteskungsfiskare"},
        {"sc": "Ceryle rudis", "en": "Pied Kingfisher", "sv": "Gråfiskare"},
        {"sc": "Merops orientalis", "en": "Green Bee-eater", "sv": "Grön dvärgbiätare"},
        {"sc": "Merops persicus", "en": "Blue-cheeked Bee-eater", "sv": "grön biätare"},
        {"sc": "Merops apiaster", "en": "European Bee-eater", "sv": "Biätare"},
        {"sc": "Upupa epops", "en": "Eurasian Hoopoe", "sv": "Härfågel"},
        {"sc": "Upupa africana", "en": "African Hoopoe", "sv": "afrikansk härfågel"},
        {"sc": "Jynx torquilla", "en": "Eurasian Wryneck", "sv": "Göktyta"},
        {"sc": "Sphyrapicus varius", "en": "Yellow-bellied Sapsucker", "sv": "Gulbröstad savspett"},
        {"sc": "Dendrocopos minor", "en": "Lesser Spotted Woodpecker", "sv": "Mindre hackspett"},
        {"sc": "Dendrocopos medius", "en": "Middle Spotted Woodpecker", "sv": "Mellanspett"},
        {"sc": "Dendrocopos leucotos", "en": "White-backed Woodpecker", "sv": "vitryggig hackspett"},
        {"sc": "Dendrocopos syriacus", "en": "Syrian Woodpecker", "sv": "Balkanspett"},
        {"sc": "Dendrocopos major", "en": "Great Spotted Woodpecker", "sv": "Större hackspett"},
        {"sc": "Picoides tridactylus", "en": "Eurasian Three-toed Woodpecker", "sv": "Tretåig hackspett"},
        {"sc": "Colaptes auratus", "en": "Northern Flicker", "sv": "Guldspett"},
        {"sc": "Dryocopus martius", "en": "Black Woodpecker", "sv": "Spillkråka"},
        {"sc": "Picus viridis", "en": "European Green Woodpecker", "sv": "Gröngöling"},
        {"sc": "Picus sharpei", "en": "Iberian Green Woodpecker", "sv": "iberisk gröngöling"},
        {"sc": "Picus canus", "en": "Grey-headed Woodpecker", "sv": "Gråspett"},
        {"sc": "Falco naumanni", "en": "Lesser Kestrel", "sv": "Rödfalk"},
        {"sc": "Falco tinnunculus", "en": "Common Kestrel", "sv": "tornfalk"},
        {"sc": "Falco sparverius", "en": "American Kestrel", "sv": "Sparvfalk"},
        {"sc": "Falco vespertinus", "en": "Red-footed Falcon", "sv": "Aftonfalk"},
        {"sc": "Falco amurensis", "en": "Amur Falcon", "sv": "Amurfalk"},
        {"sc": "Falco eleonorae", "en": "Eleonora's Falcon", "sv": "Eleonorafalk"},
        {"sc": "Falco concolor", "en": "Sooty Falcon", "sv": "Sotfalk"},
        {"sc": "Falco columbarius", "en": "Merlin", "sv": "Stenfalk"},
        {"sc": "Falco subbuteo", "en": "Eurasian Hobby", "sv": "Lärkfalk"},
        {"sc": "Falco biarmicus", "en": "Lanner Falcon", "sv": "Slagfalk"},
        {"sc": "Falco cherrug", "en": "Saker Falcon", "sv": "Tatarfalk"},
        {"sc": "Falco rusticolus", "en": "Gyrfalcon", "sv": "Jaktfalk"},
        {"sc": "Falco peregrinus", "en": "Peregrine Falcon", "sv": "Pilgrimsfalk"},
        {"sc": "Falco pelegrinoides", "en": "Barbary Falcon", "sv": "Berberfalk"},
        {"sc": "Psittacula krameri", "en": "Rose-ringed Parakeet", "sv": "Halsbandsparakit"},
        {"sc": "Agapornis fischeri", "en": "Fischer's Lovebird", "sv": "Fischers dvärgpapegoja"},
        {"sc": "Agapornis personatus", "en": "Yellow-collared Lovebird", "sv": "Svarthuvad dvärgpapegoja"},
        {"sc": "Myiopsitta monachus", "en": "Monk Parakeet", "sv": "Munkparakit"},
        {"sc": "Amazona ochrocephala", "en": "Yellow-crowned Amazon", "sv": "Gulkronad amazon"},
        {"sc": "Sayornis phoebe", "en": "Eastern Phoebe", "sv": "östlig fibi"},
        {"sc": "Contopus cooperi", "en": "Olive-sided Flycatcher", "sv": "Nordlig pivi"},
        {"sc": "Empidonax flaviventris", "en": "Yellow-bellied Flycatcher", "sv": "gulbukig empid"},
        {"sc": "Empidonax virescens", "en": "Acadian Flycatcher", "sv": "Akadempid"},
        {"sc": "Empidonax alnorum", "en": "Alder Flycatcher", "sv": "Alempid"},
        {"sc": "Empidonax minimus", "en": "Least Flycatcher", "sv": "Dvärgempid"},
        {"sc": "Tyrannus savana", "en": "Fork-tailed Flycatcher", "sv": "Gaffelstjärtstyrann"},
        {"sc": "Tyrannus tyrannus", "en": "Eastern Kingbird", "sv": "Östlig kungstyrann"},
        {"sc": "Sericornis rufescens", "en": "Vogelkop Scrubwren", "sv": "Vogelkopbusksmyg"},
        {"sc": "Tchagra senegalus", "en": "Black-crowned Tchagra", "sv": "Svartkronad tchagra"},
        {"sc": "Lanius cristatus", "en": "Brown Shrike", "sv": "Brun törnskata"},
        {"sc": "Lanius collurio", "en": "Red-backed Shrike", "sv": "Törnskata"},
        {"sc": "Lanius isabellinus", "en": "Isabelline Shrike", "sv": "Isabellatörnskata"},
        {"sc": "Lanius phoenicuroides", "en": "Red-tailed Shrike", "sv": "turkestantörnskata"},
        {"sc": "Lanius schach", "en": "Long-tailed Shrike", "sv": "Rostgumpad törnskata"},
        {"sc": "Lanius minor", "en": "Lesser Grey Shrike", "sv": "Svartpannad törnskata"},
        {"sc": "Lanius excubitor", "en": "Great Grey Shrike", "sv": "Varfågel"},
        {"sc": "Lanius meridionalis", "en": "Southern Grey Shrike", "sv": "iberisk varfågel/ökenvarfågel"},
        {"sc": "Lanius pallidirostris", "en": "Steppe Grey Shrike", "sv": "saxaulvarfågel"},
        {"sc": "Lanius senator", "en": "Woodchat Shrike", "sv": "Rödhuvad törnskata"},
        {"sc": "Lanius nubicus", "en": "Masked Shrike", "sv": "Masktörnskata"},
        {"sc": "Vireo griseus", "en": "White-eyed Vireo", "sv": "Vitögd vireo"},
        {"sc": "Vireo flavifrons", "en": "Yellow-throated Vireo", "sv": "Gulstrupig vireo"},
        {"sc": "Vireo solitarius", "en": "Blue-headed Vireo", "sv": "glasögonvireo"},
        {"sc": "Vireo philadelphicus", "en": "Philadelphia Vireo", "sv": "Kanadavireo"},
        {"sc": "Vireo olivaceus", "en": "Red-eyed Vireo", "sv": "Rödögd vireo"},
        {"sc": "Oriolus oriolus", "en": "Eurasian Golden Oriole", "sv": "Sommargylling"},
        {"sc": "Perisoreus infaustus", "en": "Siberian Jay", "sv": "Lavskrika"},
        {"sc": "Garrulus glandarius", "en": "Eurasian Jay", "sv": "Nötskrika"},
        {"sc": "Cyanopica cooki", "en": "Iberian Magpie", "sv": "iberisk blåskata"},
        {"sc": "Pica pica", "en": "Eurasian Magpie", "sv": "skata"},
        {"sc": "Nucifraga caryocatactes", "en": "Spotted Nutcracker", "sv": "Nötkråka"},
        {"sc": "Pyrrhocorax pyrrhocorax", "en": "Red-billed Chough", "sv": "Alpkråka"},
        {"sc": "Pyrrhocorax graculus", "en": "Alpine Chough", "sv": "Alpkaja"},
        {"sc": "Coloeus monedula", "en": "Western Jackdaw", "sv": "Kaja"},
        {"sc": "Coloeus dauuricus", "en": "Daurian Jackdaw", "sv": "Klippkaja"},
        {"sc": "Corvus splendens", "en": "House Crow", "sv": "Huskråka"},
        {"sc": "Corvus frugilegus", "en": "Rook", "sv": "Råka"},
        {"sc": "Corvus corone", "en": "Carrion Crow", "sv": "Svartkråka"},
        {"sc": "Corvus cornix", "en": "Hooded Crow", "sv": "Gråkråka"},
        {"sc": "Corvus corax", "en": "Northern Raven", "sv": "Korp"},
        {"sc": "Corvus rhipidurus", "en": "Fan-tailed Raven", "sv": "Kortstjärtad korp"},
        {"sc": "Bombycilla garrulus", "en": "Bohemian Waxwing", "sv": "Sidensvans"},
        {"sc": "Bombycilla cedrorum", "en": "Cedar Waxwing", "sv": "Indiansidensvans"},
        {"sc": "Periparus ater", "en": "Coal Tit", "sv": "Svartmes"},
        {"sc": "Lophophanes cristatus", "en": "European Crested Tit", "sv": "Tofsmes"},
        {"sc": "Poecile lugubris", "en": "Sombre Tit", "sv": "balkanmes"},
        {"sc": "Poecile palustris", "en": "Marsh Tit", "sv": "Entita"},
        {"sc": "Poecile montanus", "en": "Willow Tit", "sv": "talltita"},
        {"sc": "Poecile cinctus", "en": "Grey-headed Chickadee", "sv": "Lappmes"},
        {"sc": "Cyanistes teneriffae", "en": "African Blue Tit", "sv": "Koboltmes"},
        {"sc": "Cyanistes caeruleus", "en": "Eurasian Blue Tit", "sv": "Blåmes"},
        {"sc": "Cyanistes cyanus", "en": "Azure Tit", "sv": "Azurmes"},
        {"sc": "Parus major", "en": "Great Tit", "sv": "talgoxe"},
        {"sc": "Remiz pendulinus", "en": "Eurasian Penduline Tit", "sv": "Pungmes"},
        {"sc": "Panurus biarmicus", "en": "Bearded Reedling", "sv": "Skäggmes"},
        {"sc": "Alaemon alaudipes", "en": "Greater Hoopoe-Lark", "sv": "Härfågellärka"},
        {"sc": "Ammomanes deserti", "en": "Desert Lark", "sv": "Stenökenlärka"},
        {"sc": "Ammomanes cinctura", "en": "Bar-tailed Lark", "sv": "Sandökenlärka"},
        {"sc": "Lullula arborea", "en": "Woodlark", "sv": "Trädlärka"},
        {"sc": "Alauda leucoptera", "en": "White-winged Lark", "sv": "Vitvingad lärka"},
        {"sc": "Alauda arvensis", "en": "Eurasian Skylark", "sv": "Sånglärka"},
        {"sc": "Galerida theklae", "en": "Thekla Lark", "sv": "Lagerlärka"},
        {"sc": "Galerida cristata", "en": "Crested Lark", "sv": "Tofslärka"},
        {"sc": "Eremophila alpestris", "en": "Horned Lark", "sv": "Berglärka"},
        {"sc": "Eremophila bilopha", "en": "Temminck's Lark", "sv": "Ökenberglärka"},
        {"sc": "Calandrella brachydactyla", "en": "Greater Short-toed Lark", "sv": "Korttålärka"},
        {"sc": "Melanocorypha bimaculata", "en": "Bimaculated Lark", "sv": "Asiatisk kalanderlärka"},
        {"sc": "Melanocorypha calandra", "en": "Calandra Lark", "sv": "Kalanderlärka"},
        {"sc": "Melanocorypha yeltoniensis", "en": "Black Lark", "sv": "Svartlärka"},
        {"sc": "Chersophilus duponti", "en": "Dupont's Lark", "sv": "Dupontlärka"},
        {"sc": "Alaudala rufescens", "en": "Lesser Short-toed Lark", "sv": "dvärglärka"},
        {"sc": "Riparia paludicola", "en": "Brown-throated Martin", "sv": "Brunstrupig backsvala"},
        {"sc": "Riparia riparia", "en": "Sand Martin", "sv": "Backsvala"},
        {"sc": "Riparia diluta", "en": "Pale Martin", "sv": "Blek backsvala"},
        {"sc": "Tachycineta bicolor", "en": "Tree Swallow", "sv": "Trädsvala"},
        {"sc": "Progne subis", "en": "Purple Martin", "sv": "Blå storsvala"},
        {"sc": "Hirundo rustica", "en": "Barn Swallow", "sv": "Ladusvala"},
        {"sc": "Ptyonoprogne rupestris", "en": "Eurasian Crag Martin", "sv": "Klippsvala"},
        {"sc": "Ptyonoprogne fuligula", "en": "Rock Martin", "sv": "Afrikansk klippsvala"},
        {"sc": "Delichon urbicum", "en": "Common House Martin", "sv": "Hussvala"},
        {"sc": "Cecropis daurica", "en": "Red-rumped Swallow", "sv": "Rostgumpsvala"},
        {"sc": "Petrochelidon pyrrhonota", "en": "American Cliff Swallow", "sv": "Stensvala"},
        {"sc": "Petrochelidon fulva", "en": "Cave Swallow", "sv": "grottsvala"},
        {"sc": "Cettia cetti", "en": "Cetti's Warbler", "sv": "Cettisångare"},
        {"sc": "Aegithalos caudatus", "en": "Long-tailed Tit", "sv": "Stjärtmes"},
        {"sc": "Phylloscopus trochilus", "en": "Willow Warbler", "sv": "Lövsångare"},
        {"sc": "Phylloscopus collybita", "en": "Common Chiffchaff", "sv": "Gransångare"},
        {"sc": "Phylloscopus ibericus", "en": "Iberian Chiffchaff", "sv": "Iberisk gransångare"},
        {"sc": "Phylloscopus canariensis", "en": "Canary Islands Chiffchaff", "sv": "Kanariegransångare"},
        {"sc": "Phylloscopus sindianus", "en": "Mountain Chiffchaff", "sv": "Berggransångare"},
        {"sc": "Phylloscopus neglectus", "en": "Plain Leaf Warbler", "sv": "Dvärgsångare"},
        {"sc": "Phylloscopus bonelli", "en": "Western Bonelli's Warbler", "sv": "Bergsångare"},
        {"sc": "Phylloscopus orientalis", "en": "Eastern Bonelli's Warbler", "sv": "Balkansångare"},
        {"sc": "Phylloscopus sibilatrix", "en": "Wood Warbler", "sv": "Grönsångare"},
        {"sc": "Phylloscopus fuscatus", "en": "Dusky Warbler", "sv": "Brunsångare"},
        {"sc": "Phylloscopus schwarzi", "en": "Radde's Warbler", "sv": "Videsångare"},
        {"sc": "Phylloscopus proregulus", "en": "Pallas's Leaf Warbler", "sv": "Kungsfågelsångare"},
        {"sc": "Phylloscopus inornatus", "en": "Yellow-browed Warbler", "sv": "tajgasångare"},
        {"sc": "Phylloscopus humei", "en": "Hume's Leaf Warbler", "sv": "bergtajgasångare"},
        {"sc": "Phylloscopus borealis", "en": "Arctic Warbler", "sv": "Nordsångare"},
        {"sc": "Phylloscopus nitidus", "en": "Green Warbler", "sv": "kaukasisk lundsångare"},
        {"sc": "Phylloscopus trochiloides", "en": "Greenish Warbler", "sv": "Lundsångare"},
        {"sc": "Phylloscopus plumbeitarsus", "en": "Two-barred Warbler", "sv": "sibirisk lundsångare"},
        {"sc": "Phylloscopus coronatus", "en": "Eastern Crowned Warbler", "sv": "Östlig kronsångare"},
        {"sc": "Acrocephalus arundinaceus", "en": "Great Reed Warbler", "sv": "Trastsångare"},
        {"sc": "Acrocephalus melanopogon", "en": "Moustached Warbler", "sv": "Kaveldunsångare"},
        {"sc": "Acrocephalus paludicola", "en": "Aquatic Warbler", "sv": "Vattensångare"},
        {"sc": "Acrocephalus schoenobaenus", "en": "Sedge Warbler", "sv": "Sävsångare"},
        {"sc": "Acrocephalus agricola", "en": "Paddyfield Warbler", "sv": "Fältsångare"},
        {"sc": "Acrocephalus dumetorum", "en": "Blyth's Reed Warbler", "sv": "Busksångare"},
        {"sc": "Acrocephalus scirpaceus", "en": "Eurasian Reed Warbler", "sv": "Rörsångare"},
        {"sc": "Acrocephalus palustris", "en": "Marsh Warbler", "sv": "Kärrsångare"},
        {"sc": "Iduna aedon", "en": "Thick-billed Warbler", "sv": "Tjocknäbbad sångare"},
        {"sc": "Iduna caligata", "en": "Booted Warbler", "sv": "Stäppsångare"},
        {"sc": "Iduna rama", "en": "Sykes's Warbler", "sv": "Saxaulsångare"},
        {"sc": "Iduna pallida", "en": "Eastern Olivaceous Warbler", "sv": "Eksångare"},
        {"sc": "Iduna opaca", "en": "Western Olivaceous Warbler", "sv": "Macchiasångare"},
        {"sc": "Hippolais languida", "en": "Upcher's Warbler", "sv": "Orientsångare"},
        {"sc": "Hippolais olivetorum", "en": "Olive-tree Warbler", "sv": "Olivsångare"},
        {"sc": "Hippolais polyglotta", "en": "Melodious Warbler", "sv": "Polyglottsångare"},
        {"sc": "Hippolais icterina", "en": "Icterine Warbler", "sv": "Härmsångare"},
        {"sc": "Locustella davidi", "en": "Baikal Bush Warbler", "sv": "Manchurisk smygsångare"},
        {"sc": "Locustella naevia", "en": "Common Grasshopper Warbler", "sv": "gräshoppsångare"},
        {"sc": "Locustella fluviatilis", "en": "River Warbler", "sv": "Flodsångare"},
        {"sc": "Locustella luscinioides", "en": "Savi's Warbler", "sv": "Vassångare"},
        {"sc": "Locustella lanceolata", "en": "Lanceolated Warbler", "sv": "Träsksångare"},
        {"sc": "Locustella certhiola", "en": "Pallas's Grasshopper Warbler", "sv": "Starrsångare"},
        {"sc": "Locustella fasciolata", "en": "Gray's Grasshopper Warbler", "sv": "Större flodsångare"},
        {"sc": "Cisticola juncidis", "en": "Zitting Cisticola", "sv": "Grässångare"},
        {"sc": "Prinia gracilis", "en": "Graceful Prinia", "sv": "streckig prinia"},
        {"sc": "Leiothrix lutea", "en": "Red-billed Leiothrix", "sv": "rödnäbbad sångtimalia"},
        {"sc": "Sylvia atricapilla", "en": "Eurasian Blackcap", "sv": "Svarthätta"},
        {"sc": "Sylvia borin", "en": "Garden Warbler", "sv": "Trädgårdssångare"},
        {"sc": "Sylvia nisoria", "en": "Barred Warbler", "sv": "Höksångare"},
        {"sc": "Sylvia curruca", "en": "Lesser Whitethroat", "sv": "ärtsångare"},
        {"sc": "Sylvia minula", "en": "Desert Whitethroat", "sv": "ökenärtsångare"},
        {"sc": "Sylvia hortensis", "en": "Western Orphean Warbler", "sv": "Herdesångare"},
        {"sc": "Sylvia crassirostris", "en": "Eastern Orphean Warbler", "sv": "Mästersångare"},
        {"sc": "Sylvia nana", "en": "Asian Desert Warbler", "sv": "Ökensångare"},
        {"sc": "Sylvia deserti", "en": "African Desert Warbler", "sv": "Saharasångare"},
        {"sc": "Sylvia communis", "en": "Common Whitethroat", "sv": "Törnsångare"},
        {"sc": "Sylvia undata", "en": "Dartford Warbler", "sv": "Provencesångare"},
        {"sc": "Sylvia sarda", "en": "Marmora's Warbler", "sv": "Sardinsk sångare"},
        {"sc": "Sylvia balearica", "en": "Balearic Warbler", "sv": "Balearisk sångare"},
        {"sc": "Sylvia deserticola", "en": "Tristram's Warbler", "sv": "Atlassångare"},
        {"sc": "Sylvia conspicillata", "en": "Spectacled Warbler", "sv": "Glasögonsångare"},
        {"sc": "Sylvia cantillans", "en": "Subalpine Warbler", "sv": "Rödstrupig sångare"},
        {"sc": "Sylvia subalpina", "en": "Moltoni's Warbler", "sv": "Moltonisångare"},
        {"sc": "Sylvia melanocephala", "en": "Sardinian Warbler", "sv": "Sammetshätta"},
        {"sc": "Sylvia mystacea", "en": "Menetries's Warbler", "sv": "Östlig sammetshätta"},
        {"sc": "Sylvia ruppeli", "en": "Rüppell's Warbler", "sv": "Svarthakad sångare"},
        {"sc": "Sylvia melanothorax", "en": "Cyprus Warbler", "sv": "Cypernsångare"},
        {"sc": "Regulus ignicapilla", "en": "Common Firecrest", "sv": "Brandkronad kungsfågel"},
        {"sc": "Regulus regulus", "en": "Goldcrest", "sv": "Kungsfågel"},
        {"sc": "Regulus madeirensis", "en": "Madeira Firecrest", "sv": "Madeirakungsfågel"},
        {"sc": "Regulus calendula", "en": "Ruby-crowned Kinglet", "sv": "Rödkronad kungsfågel"},
        {"sc": "Cistothorus palustris", "en": "Marsh Wren", "sv": "Kärrgärdsmyg"},
        {"sc": "Troglodytes troglodytes", "en": "Eurasian Wren", "sv": "Gärdsmyg"},
        {"sc": "Sitta europaea", "en": "Eurasian Nuthatch", "sv": "Nötväcka"},
        {"sc": "Sitta arctica", "en": "Siberian Nuthatch", "sv": "jakutisk nötväcka"},
        {"sc": "Sitta whiteheadi", "en": "Corsican Nuthatch", "sv": "Korsikansk nötväcka"},
        {"sc": "Sitta krueperi", "en": "Krüper's Nuthatch", "sv": "Krüpers nötväcka"},
        {"sc": "Sitta canadensis", "en": "Red-breasted Nuthatch", "sv": "Rödbröstad nötväcka"},
        {"sc": "Sitta neumayer", "en": "Western Rock Nuthatch", "sv": "Klippnötväcka"},
        {"sc": "Tichodroma muraria", "en": "Wallcreeper", "sv": "Murkrypare"},
        {"sc": "Certhia familiaris", "en": "Eurasian Treecreeper", "sv": "Trädkrypare"},
        {"sc": "Certhia brachydactyla", "en": "Short-toed Treecreeper", "sv": "Trädgårdsträdkrypare"},
        {"sc": "Dumetella carolinensis", "en": "Grey Catbird", "sv": "Grå kattfågel"},
        {"sc": "Mimus polyglottos", "en": "Northern Mockingbird", "sv": "Nordlig härmtrast"},
        {"sc": "Toxostoma rufum", "en": "Brown Thrasher", "sv": "Rödbrun härmtrast"},
        {"sc": "Acridotheres cristatellus", "en": "Crested Myna", "sv": "kinesisk majna"},
        {"sc": "Agropsar sturninus", "en": "Daurian Starling", "sv": "Amurstare"},
        {"sc": "Pastor roseus", "en": "Rosy Starling", "sv": "Rosenstare"},
        {"sc": "Sturnus vulgaris", "en": "Common Starling", "sv": "Stare"},
        {"sc": "Sturnus unicolor", "en": "Spotless Starling", "sv": "Svartstare"},
        {"sc": "Lamprotornis caudatus", "en": "Long-tailed Glossy Starling", "sv": "Långstjärtad glansstare"},
        {"sc": "Geokichla sibirica", "en": "Siberian Thrush", "sv": "Sibirisk trast"},
        {"sc": "Zoothera aurea", "en": "White's Thrush", "sv": "guldtrast"},
        {"sc": "Zoothera dauma", "en": "Scaly Thrush", "sv": "tigertrast"},
        {"sc": "Ixoreus naevius", "en": "Varied Thrush", "sv": "Sitkatrast"},
        {"sc": "Catharus fuscescens", "en": "Veery", "sv": "Rostskogstrast"},
        {"sc": "Catharus minimus", "en": "Grey-cheeked Thrush", "sv": "Gråkindad skogstrast"},
        {"sc": "Catharus bicknelli", "en": "Bicknell's Thrush", "sv": "Bicknellskogstrast"},
        {"sc": "Catharus ustulatus", "en": "Swainson's Thrush", "sv": "Beigekindad skogstrast"},
        {"sc": "Catharus guttatus", "en": "Hermit Thrush", "sv": "Eremitskogstrast"},
        {"sc": "Hylocichla mustelina", "en": "Wood Thrush", "sv": "Fläckskogstrast"},
        {"sc": "Turdus unicolor", "en": "Tickell's Thrush", "sv": "Gråtrast"},
        {"sc": "Turdus torquatus", "en": "Ring Ouzel", "sv": "Ringtrast"},
        {"sc": "Turdus merula", "en": "Common Blackbird", "sv": ""},
        {"sc": "Turdus obscurus", "en": "Eyebrowed Thrush", "sv": "Gråhalsad trast"},
        {"sc": "Turdus pallidus", "en": "Pale Thrush", "sv": "Amurtrast"},
        {"sc": "Turdus atrogularis", "en": "Black-throated Thrush", "sv": "svarthalsad trast"},
        {"sc": "Turdus ruficollis", "en": "Red-throated Thrush", "sv": "rödhalsad trast"},
        {"sc": "Turdus naumanni", "en": "Naumann's Thrush", "sv": "rödtrast"},
        {"sc": "Turdus eunomus", "en": "Dusky Thrush", "sv": "Bruntrast"},
        {"sc": "Turdus pilaris", "en": "Fieldfare", "sv": "Björktrast"},
        {"sc": "Turdus iliacus", "en": "Redwing", "sv": "Rödvingetrast"},
        {"sc": "Turdus philomelos", "en": "Song Thrush", "sv": "Taltrast"},
        {"sc": "Turdus viscivorus", "en": "Mistle Thrush", "sv": "Dubbeltrast"},
        {"sc": "Turdus migratorius", "en": "American Robin", "sv": "Vandringstrast"},
        {"sc": "Cercotrichas galactotes", "en": "Rufous-tailed Scrub Robin", "sv": "Trädnäktergal"},
        {"sc": "Muscicapa striata", "en": "Spotted Flycatcher", "sv": "Grå flugsnappare"},
        {"sc": "Muscicapa dauurica", "en": "Asian Brown Flycatcher", "sv": "Glasögonflugsnappare"},
        {"sc": "Erithacus rubecula", "en": "European Robin", "sv": "Rödhake"},
        {"sc": "Larvivora cyane", "en": "Siberian Blue Robin", "sv": "Blånäktergal"},
        {"sc": "Larvivora sibilans", "en": "Rufous-tailed Robin", "sv": "Drillnäktergal"},
        {"sc": "Luscinia svecica", "en": "Bluethroat", "sv": "Blåhake"},
        {"sc": "Luscinia luscinia", "en": "Thrush Nightingale", "sv": "Näktergal"},
        {"sc": "Luscinia megarhynchos", "en": "Common Nightingale", "sv": "Sydnäktergal"},
        {"sc": "Irania gutturalis", "en": "White-throated Robin", "sv": "Vitstrupig näktergal"},
        {"sc": "Calliope calliope", "en": "Siberian Rubythroat", "sv": "Rubinnäktergal"},
        {"sc": "Tarsiger cyanurus", "en": "Red-flanked Bluetail", "sv": "tajgablåstjärt"},
        {"sc": "Ficedula hypoleuca", "en": "European Pied Flycatcher", "sv": "Svartvit flugsnappare"},
        {"sc": "Ficedula speculigera", "en": "Atlas Pied Flycatcher", "sv": "Atlasflugsnappare"},
        {"sc": "Ficedula albicollis", "en": "Collared Flycatcher", "sv": "Halsbandsflugsnappare"},
        {"sc": "Ficedula semitorquata", "en": "Semicollared Flycatcher", "sv": "Balkanflugsnappare"},
        {"sc": "Ficedula parva", "en": "Red-breasted Flycatcher", "sv": "Mindre flugsnappare"},
        {"sc": "Ficedula albicilla", "en": "Taiga Flycatcher", "sv": "tajgaflugsnappare"},
        {"sc": "Phoenicurus erythronotus", "en": "Eversmann's Redstart", "sv": "altajrödstjärt"},
        {"sc": "Phoenicurus ochruros", "en": "Black Redstart", "sv": "Svart rödstjärt"},
        {"sc": "Phoenicurus phoenicurus", "en": "Common Redstart", "sv": "Rödstjärt"},
        {"sc": "Phoenicurus moussieri", "en": "Moussier's Redstart", "sv": "Diademrödstjärt"},
        {"sc": "Monticola saxatilis", "en": "Common Rock Thrush", "sv": "Stentrast"},
        {"sc": "Monticola solitarius", "en": "Blue Rock Thrush", "sv": "Blåtrast"},
        {"sc": "Saxicola rubetra", "en": "Whinchat", "sv": "Buskskvätta"},
        {"sc": "Saxicola dacotiae", "en": "Canary Islands Stonechat", "sv": "Kanariebuskskvätta"},
        {"sc": "Saxicola rubicola", "en": "European Stonechat", "sv": "Svarthakad buskskvätta"},
        {"sc": "Saxicola maurus", "en": "Siberian Stonechat", "sv": "vitgumpad buskskvätta"},
        {"sc": "Saxicola stejnegeri", "en": "Stejneger's Stonechat", "sv": "Stejnegers buskskvätta"},
        {"sc": "Saxicola torquatus", "en": "African Stonechat", "sv": "afrikansk buskskvätta"},
        {"sc": "Saxicola caprata", "en": "Pied Bush Chat", "sv": "Svart buskskvätta"},
        {"sc": "Oenanthe oenanthe", "en": "Northern Wheatear", "sv": "Stenskvätta"},
        {"sc": "Oenanthe isabellina", "en": "Isabelline Wheatear", "sv": "Isabellastenskvätta"},
        {"sc": "Oenanthe deserti", "en": "Desert Wheatear", "sv": "Ökenstenskvätta"},
        {"sc": "Oenanthe hispanica", "en": "Black-eared Wheatear", "sv": "Medelhavsstenskvätta"},
        {"sc": "Oenanthe cypriaca", "en": "Cyprus Wheatear", "sv": "Cypernstenskvätta"},
        {"sc": "Oenanthe pleschanka", "en": "Pied Wheatear", "sv": "Nunnestenskvätta"},
        {"sc": "Oenanthe moesta", "en": "Red-rumped Wheatear", "sv": "Berberstenskvätta"},
        {"sc": "Oenanthe leucura", "en": "Black Wheatear", "sv": "Svart stenskvätta"},
        {"sc": "Oenanthe leucopyga", "en": "White-crowned Wheatear", "sv": "Vitkronad stenskvätta"},
        {"sc": "Oenanthe finschii", "en": "Finsch's Wheatear", "sv": "Finschstenskvätta"},
        {"sc": "Oenanthe xanthoprymna", "en": "Kurdish Wheatear", "sv": "Kurdstenskvätta"},
        {"sc": "Cinclus cinclus", "en": "White-throated Dipper", "sv": "Strömstare"},
        {"sc": "Passer domesticus", "en": "House Sparrow", "sv": "Gråsparv"},
        {"sc": "Passer italiae", "en": "Italian Sparrow", "sv": "Italiensk sparv"},
        {"sc": "Passer hispaniolensis", "en": "Spanish Sparrow", "sv": "Spansk sparv"},
        {"sc": "Passer moabiticus", "en": "Dead Sea Sparrow", "sv": "Tamarisksparv"},
        {"sc": "Passer montanus", "en": "Eurasian Tree Sparrow", "sv": "Pilfink"},
        {"sc": "Petronia petronia", "en": "Rock Sparrow", "sv": "Stensparv"},
        {"sc": "Montifringilla nivalis", "en": "White-winged Snowfinch", "sv": "Snöfink"},
        {"sc": "Ploceus melanocephalus", "en": "Black-headed Weaver", "sv": "Svarthuvad vävare"},
        {"sc": "Euplectes afer", "en": "Yellow-crowned Bishop", "sv": "gulkronad eldvävare"},
        {"sc": "Estrilda melpoda", "en": "Orange-cheeked Waxbill", "sv": "Orangekindad astrild"},
        {"sc": "Estrilda astrild", "en": "Common Waxbill", "sv": "Helenaastrild"},
        {"sc": "Amandava amandava", "en": "Red Avadavat", "sv": "Röd tigerfink"},
        {"sc": "Lonchura malacca", "en": "Tricolored Munia", "sv": "trefärgad munia"},
        {"sc": "Lonchura atricapilla", "en": "Chestnut Munia", "sv": "svarthuvad munia"},
        {"sc": "Prunella collaris", "en": "Alpine Accentor", "sv": "Alpjärnsparv"},
        {"sc": "Prunella montanella", "en": "Siberian Accentor", "sv": "Sibirisk järnsparv"},
        {"sc": "Prunella ocularis", "en": "Radde's Accentor", "sv": "Svartkronad järnsparv"},
        {"sc": "Prunella atrogularis", "en": "Black-throated Accentor", "sv": "Svartstrupig järnsparv"},
        {"sc": "Prunella modularis", "en": "Dunnock", "sv": "Järnsparv"},
        {"sc": "Motacilla flava", "en": "Western Yellow Wagtail", "sv": "gulärla"},
        {"sc": "Motacilla tschutschensis", "en": "Eastern Yellow Wagtail", "sv": "östlig gulärla"},
        {"sc": "Motacilla citreola", "en": "Citrine Wagtail", "sv": "Citronärla"},
        {"sc": "Motacilla cinerea", "en": "Grey Wagtail", "sv": "Forsärla"},
        {"sc": "Motacilla alba", "en": "White Wagtail", "sv": "sädesärla"},
        {"sc": "Anthus richardi", "en": "Richard's Pipit", "sv": "Större piplärka"},
        {"sc": "Anthus godlewskii", "en": "Blyth's Pipit", "sv": "Mongolpiplärka"},
        {"sc": "Anthus campestris", "en": "Tawny Pipit", "sv": "Fältpiplärka"},
        {"sc": "Anthus similis", "en": "Long-billed Pipit", "sv": "Långnäbbad piplärka"},
        {"sc": "Anthus pratensis", "en": "Meadow Pipit", "sv": "Ängspiplärka"},
        {"sc": "Anthus trivialis", "en": "Tree Pipit", "sv": "Trädpiplärka"},
        {"sc": "Anthus hodgsoni", "en": "Olive-backed Pipit", "sv": "Sibirisk piplärka"},
        {"sc": "Anthus gustavi", "en": "Pechora Pipit", "sv": "Tundrapiplärka"},
        {"sc": "Anthus cervinus", "en": "Red-throated Pipit", "sv": "Rödstrupig piplärka"},
        {"sc": "Anthus rubescens", "en": "Buff-bellied Pipit", "sv": "Hedpiplärka"},
        {"sc": "Anthus spinoletta", "en": "Water Pipit", "sv": "Vattenpiplärka"},
        {"sc": "Anthus petrosus", "en": "Eurasian Rock Pipit", "sv": "Skärpiplärka"},
        {"sc": "Anthus berthelotii", "en": "Berthelot's Pipit", "sv": "Kanariepiplärka"},
        {"sc": "Fringilla coelebs", "en": "Common Chaffinch", "sv": "Bofink"},
        {"sc": "Fringilla teydea", "en": "Blue Chaffinch", "sv": "blåfink"},
        {"sc": "Fringilla montifringilla", "en": "Brambling", "sv": "Bergfink"},
        {"sc": "Hesperiphona vespertina", "en": "Evening Grosbeak", "sv": "Aftonstenknäck"},
        {"sc": "Coccothraustes coccothraustes", "en": "Hawfinch", "sv": "Stenknäck"},
        {"sc": "Pinicola enucleator", "en": "Pine Grosbeak", "sv": "Tallbit"},
        {"sc": "Pyrrhula pyrrhula", "en": "Eurasian Bullfinch", "sv": "Domherre"},
        {"sc": "Pyrrhula murina", "en": "Azores Bullfinch", "sv": "Azorisk domherre"},
        {"sc": "Rhodopechys sanguineus", "en": "Eurasian Crimson-winged Finch", "sv": "asiatisk bergsökenfink"},
        {"sc": "Bucanetes githagineus", "en": "Trumpeter Finch", "sv": "Ökentrumpetare"},
        {"sc": "Bucanetes mongolicus", "en": "Mongolian Finch", "sv": "Mongolfink"},
        {"sc": "Carpodacus erythrinus", "en": "Common Rosefinch", "sv": "Rosenfink"},
        {"sc": "Carpodacus rubicilla", "en": "Great Rosefinch", "sv": "Större rosenfink"},
        {"sc": "Carpodacus roseus", "en": "Pallas's Rosefinch", "sv": "Sibirisk rosenfink"},
        {"sc": "Chloris chloris", "en": "European Greenfinch", "sv": "Grönfink"},
        {"sc": "Linaria flavirostris", "en": "Twite", "sv": "Vinterhämpling"},
        {"sc": "Linaria cannabina", "en": "Common Linnet", "sv": "Hämpling"},
        {"sc": "Acanthis flammea", "en": "Common Redpoll", "sv": "Gråsiska"},
        {"sc": "Acanthis hornemanni", "en": "Arctic Redpoll", "sv": "Snösiska"},
        {"sc": "Loxia pytyopsittacus", "en": "Parrot Crossbill", "sv": "Större korsnäbb"},
        {"sc": "Loxia scotica", "en": "Scottish Crossbill", "sv": "Skotsk korsnäbb"},
        {"sc": "Loxia curvirostra", "en": "Red Crossbill", "sv": "Mindre korsnäbb"},
        {"sc": "Loxia leucoptera", "en": "Two-barred Crossbill", "sv": "Bändelkorsnäbb"},
        {"sc": "Carduelis carduelis", "en": "European Goldfinch", "sv": "Steglits"},
        {"sc": "Carduelis citrinella", "en": "Citril Finch", "sv": "Citronsiska"},
        {"sc": "Carduelis corsicana", "en": "Corsican Finch", "sv": "korsikansk siska"},
        {"sc": "Serinus pusillus", "en": "Red-fronted Serin", "sv": "Rödpannad gulhämpling"},
        {"sc": "Serinus serinus", "en": "European Serin", "sv": "Gulhämpling"},
        {"sc": "Serinus canaria", "en": "Atlantic Canary", "sv": "kanariesiska"},
        {"sc": "Spinus spinus", "en": "Eurasian Siskin", "sv": "Grönsiska"},
        {"sc": "Seiurus aurocapilla", "en": "Ovenbird", "sv": "Rödkronad piplärksångare"},
        {"sc": "Parkesia motacilla", "en": "Louisiana Waterthrush", "sv": "Sydlig piplärksångare"},
        {"sc": "Parkesia noveboracensis", "en": "Northern Waterthrush", "sv": "Nordlig piplärksångare"},
        {"sc": "Vermivora chrysoptera", "en": "Golden-winged Warbler", "sv": "Guldvingad skogssångare"},
        {"sc": "Vermivora cyanoptera", "en": "Blue-winged Warbler", "sv": "Blåvingad skogssångare"},
        {"sc": "Mniotilta varia", "en": "Black-and-white Warbler", "sv": "Svartvit skogssångare"},
        {"sc": "Protonotaria citrea", "en": "Prothonotary Warbler", "sv": "Gyllenskogssångare"},
        {"sc": "Leiothlypis peregrina", "en": "Tennessee Warbler", "sv": "tennesseeskogssångare"},
        {"sc": "Leiothlypis celata", "en": "Orange-crowned Warbler", "sv": "Orangekronad skogssångare"},
        {"sc": "Leiothlypis ruficapilla", "en": "Nashville Warbler", "sv": "Nashvilleskogssångare"},
        {"sc": "Geothlypis philadelphia", "en": "Mourning Warbler", "sv": "Sorgskogssångare"},
        {"sc": "Geothlypis trichas", "en": "Common Yellowthroat", "sv": "gulhake"},
        {"sc": "Setophaga citrina", "en": "Hooded Warbler", "sv": "Kapuschongskogssångare"},
        {"sc": "Setophaga ruticilla", "en": "American Redstart", "sv": "Rödstjärtsskogssångare"},
        {"sc": "Setophaga tigrina", "en": "Cape May Warbler", "sv": "Brunkindad skogssångare"},
        {"sc": "Setophaga cerulea", "en": "Cerulean Warbler", "sv": "Blåvit skogssångare"},
        {"sc": "Setophaga americana", "en": "Northern Parula", "sv": "Messångare"},
        {"sc": "Setophaga magnolia", "en": "Magnolia Warbler", "sv": "Magnoliaskogssångare"},
        {"sc": "Setophaga castanea", "en": "Bay-breasted Warbler", "sv": "Brunbröstad skogssångare"},
        {"sc": "Setophaga fusca", "en": "Blackburnian Warbler", "sv": "Orangestrupig skogssångare"},
        {"sc": "Setophaga aestiva", "en": "American Yellow Warbler", "sv": "gul skogssångare"},
        {"sc": "Setophaga pensylvanica", "en": "Chestnut-sided Warbler", "sv": "Brunsidig skogssångare"},
        {"sc": "Setophaga striata", "en": "Blackpoll Warbler", "sv": "Vitkindad skogssångare"},
        {"sc": "Setophaga caerulescens", "en": "Black-throated Blue Warbler", "sv": "blåryggig skogssångare"},
        {"sc": "Setophaga palmarum", "en": "Palm Warbler", "sv": "Brunhättad skogssångare"},
        {"sc": "Setophaga pinus", "en": "Pine Warbler", "sv": "Tallskogssångare"},
        {"sc": "Setophaga coronata", "en": "Myrtle Warbler", "sv": "Gulgumpad skogssångare"},
        {"sc": "Setophaga dominica", "en": "Yellow-throated Warbler", "sv": "Gulstrupig skogssångare"},
        {"sc": "Setophaga discolor", "en": "Prairie Warbler", "sv": "Prärieskogssångare"},
        {"sc": "Setophaga virens", "en": "Black-throated Green Warbler", "sv": "grönryggig skogssångare"},
        {"sc": "Cardellina canadensis", "en": "Canada Warbler", "sv": "Kanadaskogssångare"},
        {"sc": "Cardellina pusilla", "en": "Wilson's Warbler", "sv": "Svartkronad skogssångare"},
        {"sc": "Icteria virens", "en": "Yellow-breasted Chat", "sv": "gulbröstad ikteria"},
        {"sc": "Xanthocephalus xanthocephalus", "en": "Yellow-headed Blackbird", "sv": "gulhuvad ängstrupial"},
        {"sc": "Dolichonyx oryzivorus", "en": "Bobolink", "sv": "Bobolink"},
        {"sc": "Sturnella magna", "en": "Eastern Meadowlark", "sv": "Östlig ängstrupial"},
        {"sc": "Icterus galbula", "en": "Baltimore Oriole", "sv": "Baltimoretrupial"},
        {"sc": "Molothrus ater", "en": "Brown-headed Cowbird", "sv": "Brunhuvad kostare"},
        {"sc": "Euphagus carolinus", "en": "Rusty Blackbird", "sv": "Myrtrupial"},
        {"sc": "Quiscalus quiscula", "en": "Common Grackle", "sv": "Mindre båtstjärt"},
        {"sc": "Emberiza calandra", "en": "Corn Bunting", "sv": "Kornsparv"},
        {"sc": "Emberiza citrinella", "en": "Yellowhammer", "sv": "Gulsparv"},
        {"sc": "Emberiza leucocephalos", "en": "Pine Bunting", "sv": "Tallsparv"},
        {"sc": "Emberiza cia", "en": "Rock Bunting", "sv": "Klippsparv"},
        {"sc": "Emberiza godlewskii", "en": "Godlewski's Bunting", "sv": "Mongolsparv"},
        {"sc": "Emberiza buchanani", "en": "Grey-necked Bunting", "sv": "Bergortolan"},
        {"sc": "Emberiza cineracea", "en": "Cinereous Bunting", "sv": "Gulgrå sparv"},
        {"sc": "Emberiza hortulana", "en": "Ortolan Bunting", "sv": "Ortolansparv"},
        {"sc": "Emberiza caesia", "en": "Cretzschmar's Bunting", "sv": "Rostsparv"},
        {"sc": "Emberiza cirlus", "en": "Cirl Bunting", "sv": "Häcksparv"},
        {"sc": "Emberiza striolata", "en": "Striolated Bunting", "sv": "Bergsparv"},
        {"sc": "Emberiza sahari", "en": "House Bunting", "sv": "Hussparv"},
        {"sc": "Emberiza fucata", "en": "Chestnut-eared Bunting", "sv": "Rödkindad sparv"},
        {"sc": "Emberiza pusilla", "en": "Little Bunting", "sv": "Dvärgsparv"},
        {"sc": "Emberiza chrysophrys", "en": "Yellow-browed Bunting", "sv": "Gulbrynad sparv"},
        {"sc": "Emberiza rustica", "en": "Rustic Bunting", "sv": "Videsparv"},
        {"sc": "Emberiza aureola", "en": "Yellow-breasted Bunting", "sv": "Gyllensparv"},
        {"sc": "Emberiza rutila", "en": "Chestnut Bunting", "sv": "Rödbrun sparv"},
        {"sc": "Emberiza melanocephala", "en": "Black-headed Bunting", "sv": "Svarthuvad sparv"},
        {"sc": "Emberiza bruniceps", "en": "Red-headed Bunting", "sv": "Stäppsparv"},
        {"sc": "Emberiza spodocephala", "en": "Black-faced Bunting", "sv": "Gråhuvad sparv"},
        {"sc": "Emberiza pallasi", "en": "Pallas's Reed Bunting", "sv": "Dvärgsävsparv"},
        {"sc": "Emberiza schoeniclus", "en": "Common Reed Bunting", "sv": "Sävsparv"},
        {"sc": "Passerella iliaca", "en": "Red Fox Sparrow", "sv": "rosträvsparv"},
        {"sc": "Melospiza melodia", "en": "Song Sparrow", "sv": "Sångsparv"},
        {"sc": "Melospiza lincolnii", "en": "Lincoln's Sparrow", "sv": "Lincolnsparv"},
        {"sc": "Zonotrichia leucophrys", "en": "White-crowned Sparrow", "sv": "Vitkronad sparv"},
        {"sc": "Zonotrichia albicollis", "en": "White-throated Sparrow", "sv": "Vitstrupig sparv"},
        {"sc": "Junco hyemalis", "en": "Dark-eyed Junco", "sv": "Mörkögd junco"},
        {"sc": "Passerculus sandwichensis", "en": "Savannah Sparrow", "sv": "Gulbrynad grässparv"},
        {"sc": "Chondestes grammacus", "en": "Lark Sparrow", "sv": "Lärksparv"},
        {"sc": "Pipilo erythrophthalmus", "en": "Eastern Towhee", "sv": "Brunsidig busksparv"},
        {"sc": "Calcarius lapponicus", "en": "Lapland Longspur", "sv": "Lappsparv"},
        {"sc": "Plectrophenax nivalis", "en": "Snow Bunting", "sv": "Snösparv"},
        {"sc": "Piranga rubra", "en": "Summer Tanager", "sv": "Sommartangara"},
        {"sc": "Piranga olivacea", "en": "Scarlet Tanager", "sv": "Scharlakanstangara"},
        {"sc": "Spiza americana", "en": "Dickcissel", "sv": "dickcissel"},
        {"sc": "Pheucticus ludovicianus", "en": "Rose-breasted Grosbeak", "sv": "Brokig kardinal"},
        {"sc": "Passerina caerulea", "en": "Blue Grosbeak", "sv": "Blåtjocknäbb"},
        {"sc": "Passerina cyanea", "en": "Indigo Bunting", "sv": "Indigofink"},
        {"sc": "Passerina amoena", "en": "Lazuli Bunting", "sv": "Lazulifink"}];
};