'use strict';
var exports = module.exports = {};

exports.getSpecies = function () {
    return [
        {"sc": "Cettia cetti", "en": "Cetti's Warbler", "sv": "Cettisångare"},
        {"sc": "Aegithalos caudatus", "en": "Long-tailed Tit", "sv": "Stjärtmes"},
        {"sc": "Phylloscopus trochilus", "en": "Willow Warbler", "sv": "Lövsångare"},
        {"sc": "Phylloscopus collybita", "en": "Common Chiffchaff", "sv": "Gransångare"},
        {"sc": "Phylloscopus ibericus", "en": "Iberian Chiffchaff", "sv": "Iberisk gransångare"},
        {"sc": "Phylloscopus canariensis", "en": "Canary Islands Chiffchaff", "sv": "Kanariegransångare"},
        {"sc": "Phylloscopus sindianus", "en": "Mountain Chiffchaff", "sv": "Berggransångare"},
        {"sc": "Phylloscopus neglectus", "en": "Plain Leaf Warbler", "sv": "Dvärgsångare"},
        {"sc": "Phylloscopus bonelli", "en": "Western Bonelli's Warbler", "sv": "Bergsångare"},
        {"sc": "Phylloscopus orientalis", "en": "Eastern Bonelli's Warbler", "sv": "Balkansångare"},
        {"sc": "Phylloscopus sibilatrix", "en": "Wood Warbler", "sv": "Grönsångare"},
        {"sc": "Phylloscopus fuscatus", "en": "Dusky Warbler", "sv": "Brunsångare"},
        {"sc": "Phylloscopus schwarzi", "en": "Radde's Warbler", "sv": "Videsångare"},
        {"sc": "Phylloscopus proregulus", "en": "Pallas's Leaf Warbler", "sv": "Kungsfågelsångare"},
        {"sc": "Phylloscopus inornatus", "en": "Yellow-browed Warbler", "sv": "tajgasångare"},
        {"sc": "Phylloscopus humei", "en": "Hume's Leaf Warbler", "sv": "bergtajgasångare"},
        {"sc": "Phylloscopus borealis", "en": "Arctic Warbler", "sv": "Nordsångare"},
        {"sc": "Phylloscopus nitidus", "en": "Green Warbler", "sv": "kaukasisk lundsångare"},
        {"sc": "Phylloscopus trochiloides", "en": "Greenish Warbler", "sv": "Lundsångare"},
        {"sc": "Phylloscopus plumbeitarsus", "en": "Two-barred Warbler", "sv": "sibirisk lundsångare"},
        {"sc": "Phylloscopus coronatus", "en": "Eastern Crowned Warbler", "sv": "Östlig kronsångare"},
        {"sc": "Acrocephalus arundinaceus", "en": "Great Reed Warbler", "sv": "Trastsångare"},
        {"sc": "Acrocephalus melanopogon", "en": "Moustached Warbler", "sv": "Kaveldunsångare"},
        {"sc": "Acrocephalus paludicola", "en": "Aquatic Warbler", "sv": "Vattensångare"},
        {"sc": "Acrocephalus schoenobaenus", "en": "Sedge Warbler", "sv": "Sävsångare"},
        {"sc": "Acrocephalus agricola", "en": "Paddyfield Warbler", "sv": "Fältsångare"},
        {"sc": "Acrocephalus dumetorum", "en": "Blyth's Reed Warbler", "sv": "Busksångare"},
        {"sc": "Acrocephalus scirpaceus", "en": "Eurasian Reed Warbler", "sv": "Rörsångare"},
        {"sc": "Acrocephalus palustris", "en": "Marsh Warbler", "sv": "Kärrsångare"},
        {"sc": "Iduna aedon", "en": "Thick-billed Warbler", "sv": "Tjocknäbbad sångare"},
        {"sc": "Iduna caligata", "en": "Booted Warbler", "sv": "Stäppsångare"},
        {"sc": "Iduna rama", "en": "Sykes's Warbler", "sv": "Saxaulsångare"},
        {"sc": "Iduna pallida", "en": "Eastern Olivaceous Warbler", "sv": "Eksångare"},
        {"sc": "Iduna opaca", "en": "Western Olivaceous Warbler", "sv": "Macchiasångare"},
        {"sc": "Hippolais languida", "en": "Upcher's Warbler", "sv": "Orientsångare"},
        {"sc": "Hippolais olivetorum", "en": "Olive-tree Warbler", "sv": "Olivsångare"},
        {"sc": "Hippolais polyglotta", "en": "Melodious Warbler", "sv": "Polyglottsångare"},
        {"sc": "Hippolais icterina", "en": "Icterine Warbler", "sv": "Härmsångare"},
        {"sc": "Locustella davidi", "en": "Baikal Bush Warbler", "sv": "Manchurisk smygsångare"},
        {"sc": "Locustella naevia", "en": "Common Grasshopper Warbler", "sv": "gräshoppsångare"},
        {"sc": "Locustella fluviatilis", "en": "River Warbler", "sv": "Flodsångare"},
        {"sc": "Locustella luscinioides", "en": "Savi's Warbler", "sv": "Vassångare"},
        {"sc": "Locustella lanceolata", "en": "Lanceolated Warbler", "sv": "Träsksångare"},
        {"sc": "Locustella certhiola", "en": "Pallas's Grasshopper Warbler", "sv": "Starrsångare"},
        {"sc": "Locustella fasciolata", "en": "Gray's Grasshopper Warbler", "sv": "Större flodsångare"},
        {"sc": "Cisticola juncidis", "en": "Zitting Cisticola", "sv": "Grässångare"},
        {"sc": "Prinia gracilis", "en": "Graceful Prinia", "sv": "streckig prinia"},
        {"sc": "Leiothrix lutea", "en": "Red-billed Leiothrix", "sv": "rödnäbbad sångtimalia"},
        {"sc": "Sylvia atricapilla", "en": "Eurasian Blackcap", "sv": "Svarthätta"},
        {"sc": "Sylvia borin", "en": "Garden Warbler", "sv": "Trädgårdssångare"},
        {"sc": "Sylvia nisoria", "en": "Barred Warbler", "sv": "Höksångare"},
        {"sc": "Sylvia curruca", "en": "Lesser Whitethroat", "sv": "ärtsångare"},
        {"sc": "Sylvia minula", "en": "Desert Whitethroat", "sv": "ökenärtsångare"},
        {"sc": "Sylvia hortensis", "en": "Western Orphean Warbler", "sv": "Herdesångare"},
        {"sc": "Sylvia crassirostris", "en": "Eastern Orphean Warbler", "sv": "Mästersångare"},
        {"sc": "Sylvia nana", "en": "Asian Desert Warbler", "sv": "Ökensångare"},
        {"sc": "Sylvia deserti", "en": "African Desert Warbler", "sv": "Saharasångare"},
        {"sc": "Sylvia communis", "en": "Common Whitethroat", "sv": "Törnsångare"},
        {"sc": "Sylvia undata", "en": "Dartford Warbler", "sv": "Provencesångare"},
        {"sc": "Sylvia sarda", "en": "Marmora's Warbler", "sv": "Sardinsk sångare"},
        {"sc": "Sylvia balearica", "en": "Balearic Warbler", "sv": "Balearisk sångare"},
        {"sc": "Sylvia deserticola", "en": "Tristram's Warbler", "sv": "Atlassångare"},
        {"sc": "Sylvia conspicillata", "en": "Spectacled Warbler", "sv": "Glasögonsångare"},
        {"sc": "Sylvia cantillans", "en": "Subalpine Warbler", "sv": "Rödstrupig sångare"},
        {"sc": "Sylvia subalpina", "en": "Moltoni's Warbler", "sv": "Moltonisångare"},
        {"sc": "Sylvia melanocephala", "en": "Sardinian Warbler", "sv": "Sammetshätta"},
        {"sc": "Sylvia mystacea", "en": "Menetries's Warbler", "sv": "Östlig sammetshätta"},
        {"sc": "Sylvia ruppeli", "en": "Rüppell's Warbler", "sv": "Svarthakad sångare"},
        {"sc": "Sylvia melanothorax", "en": "Cyprus Warbler", "sv": "Cypernsångare"},
        {"sc": "Seiurus aurocapilla", "en": "Ovenbird", "sv": "Rödkronad piplärksångare"},
        {"sc": "Parkesia motacilla", "en": "Louisiana Waterthrush", "sv": "Sydlig piplärksångare"},
        {"sc": "Parkesia noveboracensis", "en": "Northern Waterthrush", "sv": "Nordlig piplärksångare"},
        {"sc": "Vermivora chrysoptera", "en": "Golden-winged Warbler", "sv": "Guldvingad skogssångare"},
        {"sc": "Vermivora cyanoptera", "en": "Blue-winged Warbler", "sv": "Blåvingad skogssångare"},
        {"sc": "Mniotilta varia", "en": "Black-and-white Warbler", "sv": "Svartvit skogssångare"},
        {"sc": "Protonotaria citrea", "en": "Prothonotary Warbler", "sv": "Gyllenskogssångare"},
        {"sc": "Leiothlypis peregrina", "en": "Tennessee Warbler", "sv": "tennesseeskogssångare"},
        {"sc": "Leiothlypis celata", "en": "Orange-crowned Warbler", "sv": "Orangekronad skogssångare"},
        {"sc": "Leiothlypis ruficapilla", "en": "Nashville Warbler", "sv": "Nashvilleskogssångare"},
        {"sc": "Geothlypis philadelphia", "en": "Mourning Warbler", "sv": "Sorgskogssångare"},
        {"sc": "Geothlypis trichas", "en": "Common Yellowthroat", "sv": "gulhake"},
        {"sc": "Setophaga citrina", "en": "Hooded Warbler", "sv": "Kapuschongskogssångare"},
        {"sc": "Setophaga ruticilla", "en": "American Redstart", "sv": "Rödstjärtsskogssångare"},
        {"sc": "Setophaga tigrina", "en": "Cape May Warbler", "sv": "Brunkindad skogssångare"},
        {"sc": "Setophaga cerulea", "en": "Cerulean Warbler", "sv": "Blåvit skogssångare"},
        {"sc": "Setophaga americana", "en": "Northern Parula", "sv": "Messångare"},
        {"sc": "Setophaga magnolia", "en": "Magnolia Warbler", "sv": "Magnoliaskogssångare"},
        {"sc": "Setophaga castanea", "en": "Bay-breasted Warbler", "sv": "Brunbröstad skogssångare"},
        {"sc": "Setophaga fusca", "en": "Blackburnian Warbler", "sv": "Orangestrupig skogssångare"},
        {"sc": "Setophaga aestiva", "en": "American Yellow Warbler", "sv": "gul skogssångare"},
        {"sc": "Setophaga pensylvanica", "en": "Chestnut-sided Warbler", "sv": "Brunsidig skogssångare"},
        {"sc": "Setophaga striata", "en": "Blackpoll Warbler", "sv": "Vitkindad skogssångare"},
        {"sc": "Setophaga caerulescens", "en": "Black-throated Blue Warbler", "sv": "blåryggig skogssångare"},
        {"sc": "Setophaga palmarum", "en": "Palm Warbler", "sv": "Brunhättad skogssångare"},
        {"sc": "Setophaga pinus", "en": "Pine Warbler", "sv": "Tallskogssångare"},
        {"sc": "Setophaga coronata", "en": "Myrtle Warbler", "sv": "Gulgumpad skogssångare"},
        {"sc": "Setophaga dominica", "en": "Yellow-throated Warbler", "sv": "Gulstrupig skogssångare"},
        {"sc": "Setophaga discolor", "en": "Prairie Warbler", "sv": "Prärieskogssångare"},
        {"sc": "Setophaga virens", "en": "Black-throated Green Warbler", "sv": "grönryggig skogssångare"},
        {"sc": "Cardellina canadensis", "en": "Canada Warbler", "sv": "Kanadaskogssångare"},
        {"sc": "Cardellina pusilla", "en": "Wilson's Warbler", "sv": "Svartkronad skogssångare"}
    ];
};